// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_schema_digest.go. DO NOT EDIT.

package handlers

// SchemaDigest is the canonical digest of the north-bound contract
// assets (openapi.yaml, wsapi.json, schemas/{enums,types}.json) this
// binary was built from. Served as `schema_digest` by
// `GET /api/v1/info`; generated client type packages carry the
// same value so clients can verify type/daemon parity at connect
// time. See ADR 0028.
const SchemaDigest = "sha256:6380950906c01aea5ccd7ac0df677a3f504f4e3260d8ee5ef494df1217e8977c"
