// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_schema_digest.go. DO NOT EDIT.

package handlers

// SchemaDigest is the canonical digest of the north-bound contract
// assets (openapi.yaml, wsapi.json, schemas/{enums,types}.json) this
// binary was built from. Served as `schema_digest` by
// `GET /api/v1/info`; generated client type packages carry the
// same value so clients can verify type/daemon parity at connect
// time. See ADR 0028.
const SchemaDigest = "sha256:dab1bc420f791ac21079d0a220ed4302010dd66e9578cb360c9313edf6d36a07"
