// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_schema_digest.go. DO NOT EDIT.

package handlers

// SchemaDigest is the canonical digest of the north-bound contract
// assets (openapi.yaml, wsapi.json, schemas/{enums,types}.json) this
// binary was built from. Served as `schema_digest` by
// `GET /api/v1/info`; generated client type packages carry the
// same value so clients can verify type/daemon parity at connect
// time. See ADR 0028.
const SchemaDigest = "sha256:66cbd171d1dfade7b74e32663d80320146b407859e87e2e2d698fd22e43d8ff4"
