// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

package calculated

import "testing"

// goldenEpsilon pins each formula to its reference output at the formula's own
// rounding precision (1 or 2 decimals). It is far tighter than the historic
// ±0.2 self-referential tolerance, so the assertions catch a real divergence
// from the reference rather than merely re-measuring loom's own arithmetic.
const goldenEpsilon = 1e-9

// TestFormulasMatchReferenceGoldenValues pins each climate/battery formula to
// the value the reference produces at fixed inputs. The golden
// values were generated by running the reference formula bodies
// (model/calculated/support.py) verbatim — see the DewPoint / FrostPoint /
// Enthalpy / VaporConcentration / ApparentTemperature / OperatingVoltageLevel
// functions in that module. Any drift in the Go port surfaces here.
func TestFormulasMatchReferenceGoldenValues(t *testing.T) {
	t.Parallel()

	type golden struct {
		name string
		got  float64
		ok   bool
		want float64
	}

	// calculate_dew_point (support.py:167).
	dp2050, ok1 := DewPoint(20, 50)
	dp2560, ok2 := DewPoint(25, 60)
	dpm580, ok3 := DewPoint(-5, 80)
	// calculate_dew_point_spread (support.py:21).
	sp2050, ok4 := DewPointSpread(20, 50)
	sp2560, ok5 := DewPointSpread(25, 60)
	// calculate_frost_point (support.py:192).
	fp2050, ok6 := FrostPoint(20, 50)
	fpm580, ok7 := FrostPoint(-5, 80)
	fp0560, ok8 := FrostPoint(0.5, 60)
	// calculate_enthalpy (support.py:33).
	en2050, ok9 := Enthalpy(20, 50, DefaultPressureHPa)
	en2560, ok10 := Enthalpy(25, 60, DefaultPressureHPa)
	en3080, ok11 := Enthalpy(30, 80, 1000.0)
	// calculate_vapor_concentration (support.py:121).
	vc2050, ok12 := VaporConcentration(20, 50)
	vc2560, ok13 := VaporConcentration(25, 60)
	// calculate_apparent_temperature (support.py:142): wind-chill / heat-index / passthrough branches.
	at0520, ok14 := ApparentTemperature(5, 50, 20)
	at3060, ok15 := ApparentTemperature(30, 60, 0)
	at1850, ok16 := ApparentTemperature(18, 50, 0)
	at3570, ok17 := ApparentTemperature(35, 70, 2)
	// calculate_operating_voltage_level (support.py:213).
	ov26, ok18 := OperatingVoltageLevel(2.6, 2.2, 3.0)
	ov35, ok19 := OperatingVoltageLevel(3.5, 2.2, 3.0)
	ov20, ok20 := OperatingVoltageLevel(2.0, 2.2, 3.0)

	cases := []golden{
		{"DewPoint(20,50)", dp2050, ok1, 9.3},
		{"DewPoint(25,60)", dp2560, ok2, 16.7},
		{"DewPoint(-5,80)", dpm580, ok3, -7.9},
		{"DewPointSpread(20,50)", sp2050, ok4, 10.7},
		{"DewPointSpread(25,60)", sp2560, ok5, 8.3},
		{"FrostPoint(20,50)", fp2050, ok6, 6.6},
		{"FrostPoint(-5,80)", fpm580, ok7, -7.3},
		{"FrostPoint(0.5,60)", fp0560, ok8, -6.5},
		{"Enthalpy(20,50,1013.25)", en2050, ok9, 38.5},
		{"Enthalpy(25,60,1013.25)", en2560, ok10, 55.37},
		{"Enthalpy(30,80,1000)", en3080, ok11, 85.93},
		{"VaporConcentration(20,50)", vc2050, ok12, 8.64},
		{"VaporConcentration(25,60)", vc2560, ok13, 13.82},
		{"ApparentTemperature windchill(5,50,20)", at0520, ok14, 1.1},
		{"ApparentTemperature heatindex(30,60,0)", at3060, ok15, 32.8},
		{"ApparentTemperature passthrough(18,50,0)", at1850, ok16, 18.0},
		{"ApparentTemperature heatindex(35,70,2)", at3570, ok17, 50.3},
		{"OperatingVoltageLevel(2.6,2.2,3.0)", ov26, ok18, 50.0},
		{"OperatingVoltageLevel(3.5,2.2,3.0) clamps to 100", ov35, ok19, 100.0},
		{"OperatingVoltageLevel(2.0,2.2,3.0) clamps to 0", ov20, ok20, 0.0},
	}

	for _, c := range cases {
		if !c.ok {
			t.Errorf("%s: ok=false, want a value ≈ %g", c.name, c.want)
			continue
		}
		if diff := c.got - c.want; diff > goldenEpsilon || diff < -goldenEpsilon {
			t.Errorf("%s = %.10g, want %g (reference golden)", c.name, c.got, c.want)
		}
	}
}

// TestOperatingVoltageLevelRejectsInvalidConfig pins the reference guard: when
// voltage_max <= low_bat_limit the formula returns None (support.py:219-221).
func TestOperatingVoltageLevelRejectsInvalidConfig(t *testing.T) {
	t.Parallel()

	if _, ok := OperatingVoltageLevel(2.6, 2.2, 2.2); ok {
		t.Error("OperatingVoltageLevel must return ok=false when voltage_max <= low_bat_limit")
	}
}

// TestFeedSinkEmitsTrailingDistinctValueAfterDuplicate guards the feedSink
// debounce: its dedup only suppresses a value equal to the last EMITTED value,
// so a distinct trailing value must still reach the sink. Without a publisher or
// registered sources the recency guards are inactive, isolating the dedup path.
// A burst of [9.3, 9.3, 12.0] must emit 9.3 once and then 12.0 — the trailing
// distinct value is never dropped.
func TestFeedSinkEmitsTrailingDistinctValueAfterDuplicate(t *testing.T) {
	t.Parallel()

	// Reference dew points: DewPoint(20,50)=9.3, DewPoint(20,60)=12.0.
	first, ok := DewPoint(20, 50)
	if !ok {
		t.Fatal("DewPoint(20,50) unexpectedly returned ok=false")
	}
	trailing, ok := DewPoint(20, 60)
	if !ok {
		t.Fatal("DewPoint(20,60) unexpectedly returned ok=false")
	}
	if first == trailing {
		t.Fatalf("test setup broken: expected distinct dew points, both %g", first)
	}

	s := NewDewPointSensor()
	var emitted []float64
	s.OnUpdate(func(_, next float64) { emitted = append(emitted, next) })

	s.OnTemperature(20)
	s.OnHumidity(50) // → first (9.3): emitted
	s.OnHumidity(50) // → first again: deduped, must NOT emit
	s.OnHumidity(60) // → trailing (12.0): distinct, must emit

	if len(emitted) != 2 {
		t.Fatalf("expected exactly 2 emissions (first + trailing distinct), got %d: %v", len(emitted), emitted)
	}
	if emitted[0] != first {
		t.Errorf("first emission = %g, want %g", emitted[0], first)
	}
	if emitted[len(emitted)-1] != trailing {
		t.Errorf("trailing emission = %g, want %g (debounce dropped the last value)", emitted[len(emitted)-1], trailing)
	}
}
