// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package light

import (
	"testing"

	"github.com/SukramJ/openccu-loom/internal/model/custom"
	"github.com/SukramJ/openccu-loom/internal/model/device"
	"github.com/SukramJ/openccu-loom/pkg/hmenum"
	"github.com/SukramJ/openccu-loom/pkg/hmtypes"
)

// TestLightNilLevelDPCategoryDoesNotPanic verifies that a Light built from a
// channel without a LEVEL data point (Float == nil — a "half-formed" channel,
// e.g. a light loader that fired before the channel materialised LEVEL) reports
// its category and key without panicking. The WS custom-DP-list handler
// (GET /api/v1/devices/{addr}/cdps) dispatches Category() through the
// autogenerated forwarder to (*DataPoint[float64]).Category, which dereferenced
// its nil receiver and crashed the daemon with a 500 on such a Light.
func TestLightNilLevelDPCategoryDoesNotPanic(t *testing.T) {
	t.Parallel()

	d := device.New(device.Config{InterfaceID: "HmIP-RF", Address: "ABC0001"})
	// Channel with no LEVEL DP → Light.Float stays nil.
	ch := d.AddChannel("HmIP-BSL:3", 1, "DIMMER", hmenum.ParamsetKeyValues)
	l := New(Config{Channel: ch, Capabilities: custom.LightCapabilities{}})

	if l.Float != nil {
		t.Fatal("Light.Float must be nil when channel has no LEVEL DP")
	}
	// Same hazard as cover.Cover.Category: the autogenerated forwarder
	// dispatches through (*DataPoint).Category which dereferences its receiver.
	if got := l.Category(); got != hmenum.DataPointCategoryUndefined {
		t.Errorf("Category() with nil Float = %v, want undefined", got)
	}
	if got := l.DataPointKey(); got != (hmtypes.DataPointKey{}) {
		t.Errorf("DataPointKey() with nil Float = %v, want zero key", got)
	}
}
