// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package contract

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// consumedManifest is the set openccu-loom-client publishes: the daemon
// operations it actually calls, as "METHOD /path/{}" with every path
// parameter reduced to {}.
//
// It exists because this repository's versioning policy makes every removal a
// major bump, and the client used to refuse any daemon whose major differed.
// Both rules are individually defensible; together they locked users out. The
// API major moved 7 -> 8 -> 9 -> 10 inside one release window, and each of
// those bumps removed surface no generated client referenced — a break on
// paper, nothing broken in fact. Neither side could tell the difference,
// because nothing recorded what a client consumes.
//
// The manifest is generated by script/gen/consumed_operations.py in the client
// repository from an AST walk of its façade call sites, and that repository's
// own test fails when it goes stale. Here it is read, never written.
type consumedManifest struct {
	ClientVersion string   `json:"client_version"`
	Operations    []string `json:"operations"`
}

// pathParameter matches one {name} segment; both sides erase parameter names
// before comparing, because they are not part of the wire contract — this
// document calls one {channel_no} where the client calls it {channel}.
var pathParameter = regexp.MustCompile(`\{[^{}]*\}`)

func normaliseOperationKey(key string) string {
	return pathParameter.ReplaceAllString(key, "{}")
}

// requireManifestEnv makes an absent manifest a failure rather than a skip.
// CI sets it; a contributor's laptop does not.
//
// It exists because the first version of these guards shipped without it and
// was dead on arrival: the contract job checks out this repository only, so
// both guards skipped in every CI run and had executed exactly once, on the
// machine that wrote them. A guard that skips silently returns the same
// result whether or not the thing it checks is true — the failure this
// repository's rules name explicitly — and the bite proof did not catch it,
// because a bite proof validates the mechanism and says nothing about whether
// the mechanism is ever reached.
//
// So the skip is now a claim CI can refute. If the checkout step is renamed,
// moved or dropped, the contract job fails with a message naming it instead of
// quietly going green again.
const requireManifestEnv = "CONTRACT_REQUIRE_CLIENT_MANIFEST"

// findConsumedManifest locates the client's manifest, or reports why it could
// not. The client repository is normally checked out beside this one, and
// OPENCCU_LOOM_CLIENT_REPO overrides for CI and non-sibling layouts.
//
// Absence is a legitimate outcome locally: a contributor with only this
// repository checked out must still be able to run the contract suite. What
// absence must never do is silently pass as "nothing consumed" — that would
// classify every removal as safe, which is the exact opposite of the truth and
// worse than having no check at all. In CI, where the manifest is supposed to
// be there, absence fails.
func findConsumedManifest(t *testing.T) (path string, ok bool) {
	t.Helper()
	// An explicit override is the only candidate when it is set. Falling back
	// to the sibling path behind it would mean a run that names one checkout
	// and silently measures another — and on a developer's machine, where the
	// sibling almost always exists, that fallback hides a wrong or missing
	// override completely.
	var candidates []string
	if env := os.Getenv("OPENCCU_LOOM_CLIENT_REPO"); env != "" {
		candidates = []string{env}
	} else {
		_, thisFile, _, _ := runtime.Caller(0)
		repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
		candidates = append(candidates, filepath.Join(repoRoot, "..", "openccu-loom-client"))
	}

	for _, repo := range candidates {
		p := filepath.Join(repo, "spec", "consumed_operations.json")
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	if os.Getenv(requireManifestEnv) != "" {
		t.Fatalf("%s is set but no client manifest was found under any of %v.\n"+
			"The contract job is supposed to check out SukramJ/openccu-loom-client at its latest\n"+
			"release tag and point OPENCCU_LOOM_CLIENT_REPO at it. If that step moved or was\n"+
			"removed, these guards stop measuring anything — restore it rather than unsetting %s.",
			requireManifestEnv, candidates, requireManifestEnv)
	}
	return "", false
}

func loadConsumedManifest(t *testing.T, path string) consumedManifest {
	t.Helper()
	raw, err := os.ReadFile(path) //nolint:gosec // path resolved above from a fixed layout
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var m consumedManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(m.Operations) == 0 {
		t.Fatalf("%s lists no operations — the manifest is empty, which would classify every removal as safe", path)
	}
	return m
}

// TestConsumedOperationsAreServed is the manifest's own soundness check, and it
// runs before anything is classified against it.
//
// A manifest naming an operation this document does not serve is either stale
// or built from a different daemon generation. Either way its answers about
// what is consumed cannot be trusted, and a removal classified against it would
// be classified against fiction.
func TestConsumedOperationsAreServed(t *testing.T) {
	path, ok := findConsumedManifest(t)
	if !ok {
		t.Skip("openccu-loom-client not checked out beside this repo (set OPENCCU_LOOM_CLIENT_REPO)")
	}
	manifest := loadConsumedManifest(t, path)

	served := map[string]bool{}
	for key := range buildAPISurface(loadOpenAPISpec(t)).Operations {
		served[normaliseOperationKey(key)] = true
	}

	var unknown []string
	for _, op := range manifest.Operations {
		if !served[normaliseOperationKey(op)] {
			unknown = append(unknown, op)
		}
	}
	sort.Strings(unknown)
	if len(unknown) > 0 {
		t.Errorf("openccu-loom-client %s says it calls %d operation(s) this document does not serve:\n  %s\n\n"+
			"Either the manifest is stale (regenerate it there), or these were removed here without\n"+
			"anybody noticing the client still calls them — which is precisely the case this guard exists for.",
			manifest.ClientVersion, len(unknown), strings.Join(unknown, "\n  "))
	}
}

// TestRemovedOperationsAreReportedAgainstWhatClientsCall answers the question
// the version number could not: is a removal one a client would notice?
//
// It does not decide the bump — TestAPISurfaceChangesCarryTheRightBump owns
// that, and still demands a major for any removal. This one adds the fact that
// decision needs, and it is deliberately advisory in one direction only: a
// removal the manifest does not name is *reported as unconsumed*, never
// silently approved, because the manifest covers the clients this project
// builds and no others.
func TestRemovedOperationsAreReportedAgainstWhatClientsCall(t *testing.T) {
	path, ok := findConsumedManifest(t)
	if !ok {
		t.Skip("openccu-loom-client not checked out beside this repo (set OPENCCU_LOOM_CLIENT_REPO)")
	}
	manifest := loadConsumedManifest(t, path)

	baseline := loadAPISurfaceBaseline(t)
	current := buildAPISurface(loadOpenAPISpec(t))

	consumed := map[string]bool{}
	for _, op := range manifest.Operations {
		consumed[normaliseOperationKey(op)] = true
	}

	var breaksAClient, unconsumed []string
	for key := range baseline.Operations {
		if _, still := current.Operations[key]; still {
			continue
		}
		if consumed[normaliseOperationKey(key)] {
			breaksAClient = append(breaksAClient, key)
		} else {
			unconsumed = append(unconsumed, key)
		}
	}
	sort.Strings(breaksAClient)
	sort.Strings(unconsumed)

	if len(unconsumed) > 0 {
		t.Logf("removed, and openccu-loom-client %s calls none of them — a major bump here costs "+
			"every consumer a lockout for surface they never used:\n  %s",
			manifest.ClientVersion, strings.Join(unconsumed, "\n  "))
	}
	var unexcused []string
	for _, key := range breaksAClient {
		if _, excused := removalsBreakingAConsumedClient[key]; !excused {
			unexcused = append(unexcused, key)
		}
	}
	if len(unexcused) > 0 {
		t.Errorf("%d removed operation(s) are called by openccu-loom-client %s:\n  %s\n\n"+
			"This is a real break, not a bookkeeping one. Keep the operation, land the client's\n"+
			"replacement first, or — if the break is intended — record it in\n"+
			"removalsBreakingAConsumedClient with the reason and where the client stops calling it.\n"+
			"A released daemon without the operation leaves every installed client failing at the call.",
			len(unexcused), manifest.ClientVersion, strings.Join(unexcused, "\n  "))
	}
}

// removalsBreakingAConsumedClient records removals taken deliberately while the
// released client still calls them.
//
// It exists so the guard above can stay red by default without creating the
// cross-repo ordering it was built to remove. Without an escape the only way
// past a legitimate breaking change would be to release the client first — the
// hand-off this whole mechanism exists to make unnecessary. With one, the
// decision is written down instead of taken silently.
//
// An entry is a statement about a *released* client, so it stops being true on
// its own: once a client that no longer calls the operation is released, the
// guard sees no break and the entry is dead weight. Delete it then —
// [TestExcusedRemovalsAreStillBreaking] fails on an entry that no longer
// describes a break, for the same reason the wiring ratchet refuses an entry
// whose setter has gained a caller: a list that keeps entries it no longer
// needs stops meaning what it says.
//
// Key: "METHOD /path/{}" exactly as the surface inventory spells it. Value:
// why the removal was taken anyway, and where the client stops calling it.
var removalsBreakingAConsumedClient = map[string]string{}

// TestExcusedRemovalsAreStillBreaking keeps the escape list from outliving its
// entries.
//
// An excuse is only sound while the removal it excuses is actually detected.
// Once the client stops calling the operation — or the operation comes back —
// the entry exempts nothing, and a stale exemption is worse than none: it reads
// as a known, accepted break long after the break is gone.
func TestExcusedRemovalsAreStillBreaking(t *testing.T) {
	if len(removalsBreakingAConsumedClient) == 0 {
		return
	}
	path, ok := findConsumedManifest(t)
	if !ok {
		t.Skip("openccu-loom-client not checked out beside this repo (set OPENCCU_LOOM_CLIENT_REPO)")
	}
	manifest := loadConsumedManifest(t, path)
	consumed := map[string]bool{}
	for _, op := range manifest.Operations {
		consumed[normaliseOperationKey(op)] = true
	}
	baseline := loadAPISurfaceBaseline(t)
	current := buildAPISurface(loadOpenAPISpec(t))

	for _, key := range sortedExcuseKeys() {
		_, gone := baseline.Operations[key]
		_, back := current.Operations[key]
		switch {
		case !gone:
			t.Errorf("removalsBreakingAConsumedClient[%q] names an operation the committed baseline "+
				"does not have — nothing is being excused; drop the entry", key)
		case back:
			t.Errorf("removalsBreakingAConsumedClient[%q] names an operation the specification serves "+
				"again — the break is over; drop the entry", key)
		case !consumed[normaliseOperationKey(key)]:
			t.Errorf("removalsBreakingAConsumedClient[%q] names an operation openccu-loom-client %s "+
				"no longer calls — the break is over; drop the entry", key, manifest.ClientVersion)
		}
	}
}

func sortedExcuseKeys() []string {
	keys := make([]string, 0, len(removalsBreakingAConsumedClient))
	for k := range removalsBreakingAConsumedClient {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// loadAPISurfaceBaseline reads the committed REST inventory, the same file
// TestAPISurfaceChangesCarryTheRightBump diffs against.
func loadAPISurfaceBaseline(t *testing.T) apiSurface {
	t.Helper()
	path := apiSurfacePath(t)
	raw, err := os.ReadFile(path) //nolint:gosec // fixed testdata path
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var baseline apiSurface
	if err := json.Unmarshal(raw, &baseline); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(baseline.Operations) == 0 {
		t.Fatalf("%s holds no operations", path)
	}
	return baseline
}
