// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package contract

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// consumedManifest is the set openccu-loom-client publishes: the daemon
// operations it actually calls, as "METHOD /path/{}" with every path
// parameter reduced to {}.
//
// It exists because this repository's versioning policy makes every removal a
// major bump, and the client used to refuse any daemon whose major differed.
// Both rules are individually defensible; together they locked users out. The
// API major moved 7 -> 8 -> 9 -> 10 inside one release window, and each of
// those bumps removed surface no generated client referenced — a break on
// paper, nothing broken in fact. Neither side could tell the difference,
// because nothing recorded what a client consumes.
//
// The manifest is generated by script/gen/consumed_operations.py in the client
// repository from an AST walk of its façade call sites, and that repository's
// own test fails when it goes stale. Here it is read, never written.
type consumedManifest struct {
	ClientVersion string   `json:"client_version"`
	Operations    []string `json:"operations"`
}

// pathParameter matches one {name} segment; both sides erase parameter names
// before comparing, because they are not part of the wire contract — this
// document calls one {channel_no} where the client calls it {channel}.
var pathParameter = regexp.MustCompile(`\{[^{}]*\}`)

func normaliseOperationKey(key string) string {
	return pathParameter.ReplaceAllString(key, "{}")
}

// findConsumedManifest locates the client's manifest, or reports why it could
// not. The client repository is normally checked out beside this one, and
// OPENCCU_LOOM_CLIENT_REPO overrides for CI and non-sibling layouts.
//
// Absence is a legitimate outcome, not a failure: a contributor with only this
// repository checked out must still be able to run the contract suite. What
// absence must never do is silently pass as "nothing consumed" — that would
// classify every removal as safe, which is the exact opposite of the truth and
// worse than having no check at all.
func findConsumedManifest(t *testing.T) (path string, ok bool) {
	t.Helper()
	var candidates []string
	if env := os.Getenv("OPENCCU_LOOM_CLIENT_REPO"); env != "" {
		candidates = append(candidates, env)
	}
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
	candidates = append(candidates, filepath.Join(repoRoot, "..", "openccu-loom-client"))

	for _, repo := range candidates {
		p := filepath.Join(repo, "spec", "consumed_operations.json")
		if _, err := os.Stat(p); err == nil {
			return p, true
		}
	}
	return "", false
}

func loadConsumedManifest(t *testing.T, path string) consumedManifest {
	t.Helper()
	raw, err := os.ReadFile(path) //nolint:gosec // path resolved above from a fixed layout
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var m consumedManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(m.Operations) == 0 {
		t.Fatalf("%s lists no operations — the manifest is empty, which would classify every removal as safe", path)
	}
	return m
}

// TestConsumedOperationsAreServed is the manifest's own soundness check, and it
// runs before anything is classified against it.
//
// A manifest naming an operation this document does not serve is either stale
// or built from a different daemon generation. Either way its answers about
// what is consumed cannot be trusted, and a removal classified against it would
// be classified against fiction.
func TestConsumedOperationsAreServed(t *testing.T) {
	path, ok := findConsumedManifest(t)
	if !ok {
		t.Skip("openccu-loom-client not checked out beside this repo (set OPENCCU_LOOM_CLIENT_REPO)")
	}
	manifest := loadConsumedManifest(t, path)

	served := map[string]bool{}
	for key := range buildAPISurface(loadOpenAPISpec(t)).Operations {
		served[normaliseOperationKey(key)] = true
	}

	var unknown []string
	for _, op := range manifest.Operations {
		if !served[normaliseOperationKey(op)] {
			unknown = append(unknown, op)
		}
	}
	sort.Strings(unknown)
	if len(unknown) > 0 {
		t.Errorf("openccu-loom-client %s says it calls %d operation(s) this document does not serve:\n  %s\n\n"+
			"Either the manifest is stale (regenerate it there), or these were removed here without\n"+
			"anybody noticing the client still calls them — which is precisely the case this guard exists for.",
			manifest.ClientVersion, len(unknown), strings.Join(unknown, "\n  "))
	}
}

// TestRemovedOperationsAreReportedAgainstWhatClientsCall answers the question
// the version number could not: is a removal one a client would notice?
//
// It does not decide the bump — TestAPISurfaceChangesCarryTheRightBump owns
// that, and still demands a major for any removal. This one adds the fact that
// decision needs, and it is deliberately advisory in one direction only: a
// removal the manifest does not name is *reported as unconsumed*, never
// silently approved, because the manifest covers the clients this project
// builds and no others.
func TestRemovedOperationsAreReportedAgainstWhatClientsCall(t *testing.T) {
	path, ok := findConsumedManifest(t)
	if !ok {
		t.Skip("openccu-loom-client not checked out beside this repo (set OPENCCU_LOOM_CLIENT_REPO)")
	}
	manifest := loadConsumedManifest(t, path)

	baseline := loadAPISurfaceBaseline(t)
	current := buildAPISurface(loadOpenAPISpec(t))

	consumed := map[string]bool{}
	for _, op := range manifest.Operations {
		consumed[normaliseOperationKey(op)] = true
	}

	var breaksAClient, unconsumed []string
	for key := range baseline.Operations {
		if _, still := current.Operations[key]; still {
			continue
		}
		if consumed[normaliseOperationKey(key)] {
			breaksAClient = append(breaksAClient, key)
		} else {
			unconsumed = append(unconsumed, key)
		}
	}
	sort.Strings(breaksAClient)
	sort.Strings(unconsumed)

	if len(unconsumed) > 0 {
		t.Logf("removed, and openccu-loom-client %s calls none of them — a major bump here costs "+
			"every consumer a lockout for surface they never used:\n  %s",
			manifest.ClientVersion, strings.Join(unconsumed, "\n  "))
	}
	if len(breaksAClient) > 0 {
		t.Errorf("%d removed operation(s) are called by openccu-loom-client %s:\n  %s\n\n"+
			"This is a real break, not a bookkeeping one. Keep the operation, or land the client's\n"+
			"replacement first — a released daemon without it leaves every installed client\n"+
			"failing at the call.",
			len(breaksAClient), manifest.ClientVersion, strings.Join(breaksAClient, "\n  "))
	}
}

// loadAPISurfaceBaseline reads the committed REST inventory, the same file
// TestAPISurfaceChangesCarryTheRightBump diffs against.
func loadAPISurfaceBaseline(t *testing.T) apiSurface {
	t.Helper()
	path := apiSurfacePath(t)
	raw, err := os.ReadFile(path) //nolint:gosec // fixed testdata path
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var baseline apiSurface
	if err := json.Unmarshal(raw, &baseline); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(baseline.Operations) == 0 {
		t.Fatal(fmt.Sprintf("%s holds no operations", path))
	}
	return baseline
}
