// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Package contract hosts contract tests — assertions that pin down
// behaviour we explicitly refuse to change. Each test states a hard
// rule and fails loudly when the rule is violated.
//
// Contract tests run as part of `make test` (they have no build tag).
// The catalogue lives in tests/contract/README.md — generated by
// TestContractCatalogueIsComplete, not hand-maintained.
package contract
