// SPDX-License-Identifier: MIT
// Copyright (C) 2026 openccu-loom authors.
//
// Code generated by script/generate_profiles.py. DO NOT EDIT.

package contract

import (
	"testing"

	"github.com/SukramJ/openccu-loom/internal/model/custom"
)

// TestDeviceProfileRegistryParity pins the registered profile count to
// the number the generator observed at generation time. Drift means
// someone edited generated_profiles.go by hand — the fix is to
// regenerate, not to update this assertion.
func TestDeviceProfileRegistryParity(t *testing.T) {
	r := custom.DefaultRegistry()
	if got := r.Len(); got != custom.GeneratedProfileCount {
		t.Fatalf("registry has %d profiles, generator emitted %d", got, custom.GeneratedProfileCount)
	}
}

// TestProfileConfigCatalogParity pins the size of the auto-generated
// ProfileConfigs catalog to the value the generator observed.
func TestProfileConfigCatalogParity(t *testing.T) {
	if got := len(custom.ProfileConfigs); got != custom.GeneratedProfileConfigCount {
		t.Fatalf("ProfileConfigs has %d entries, generator emitted %d", got, custom.GeneratedProfileConfigCount)
	}
}

// TestDefaultDataPointsParity pins the number of channel-offset entries
// that DefaultDataPoints exposes.
func TestDefaultDataPointsParity(t *testing.T) {
	if got := len(custom.DefaultDataPoints); got != custom.GeneratedDefaultDataPointCount {
		t.Fatalf("DefaultDataPoints has %d entries, generator emitted %d", got, custom.GeneratedDefaultDataPointCount)
	}
}
