// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/gen_propkinds.go — DO NOT EDIT.
// Source of truth: every struct in this package that carries
// `payload:"..."` tags. Re-generate with:
//
//	go run ./script/gen_propkinds.go ./<package-path>

package device

// PropKindEntry is one descriptor row: kind / public field name / wire
// name (defaults to the field name in lower case, overridable via the
// tag's `alt=...` clause).
type PropKindEntry struct {
	Kind  string
	Field string
	Alt   string
}

// PropKindsByType holds the pre-computed descriptors. Lookup is
// idempotent: the runtime payload extractor can fall back to
// reflection if a type is missing here.
var PropKindsByType = map[string][]PropKindEntry{
	"Device": {
		{Kind: "config", Field: "RxModes", Alt: "rx_modes"},
		{Kind: "config", Field: "Updatable", Alt: ""},
		{Kind: "info", Field: "Address", Alt: "serial_number"},
		{Kind: "info", Field: "Interface", Alt: ""},
		{Kind: "info", Field: "InterfaceID", Alt: ""},
		{Kind: "info", Field: "IseID", Alt: "ise_id"},
		{Kind: "info", Field: "Manufacturer", Alt: ""},
		{Kind: "info", Field: "Model", Alt: ""},
		{Kind: "info", Field: "ModelIcon", Alt: "model_icon"},
		{Kind: "info", Field: "ModelLabel", Alt: "model_label"},
		{Kind: "info", Field: "Name", Alt: ""},
		{Kind: "info", Field: "ProductGroup", Alt: "product_group"},
		{Kind: "info", Field: "SchemaVersion", Alt: "schema_version"},
		{Kind: "info", Field: "SubModel", Alt: "sub_model"},
	},
}
