// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

//go:build ignore

// gen_propkinds — pre-compute the (kind, field-name, alt) tuples for
// every struct that uses `payload:"..."` tags, so the runtime
// reflection in `internal/payload` can be replaced with a static
// lookup in hot paths.
//
// QW-11 ships this as a *skeleton*: it parses one or more directories
// and emits a deterministic `propkinds_gen.go` file with the
// extracted descriptors per type. The file is checked in next to its
// source. The runtime decides whether to consult the static table or
// fall back to the existing reflection path — that wiring lives in
// P0-1 (`Instrument` rollout) when we know which packages are hot
// enough to warrant the optimisation.
//
// Usage:
//
//	go run ./script/gen_propkinds.go ./internal/model/device ./internal/model/hub
//
// One package per argument; the tool writes `propkinds_gen.go` into
// each. Re-running on unchanged sources is a no-op (deterministic
// output, file mtime unchanged).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

const fileHeader = `// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/gen_propkinds.go — DO NOT EDIT.
// Source of truth: every struct in this package that carries
// ` + "`" + `payload:"..."` + "`" + ` tags. Re-generate with:
//
//	go run ./script/gen_propkinds.go ./` + `<package-path>` + `

package %s

// PropKindEntry is one descriptor row: kind / public field name / wire
// name (defaults to the field name in lower case, overridable via the
// tag's ` + "`" + `alt=...` + "`" + ` clause).
type PropKindEntry struct {
	Kind  string
	Field string
	Alt   string
}

// PropKindsByType holds the pre-computed descriptors. Lookup is
// idempotent: the runtime payload extractor can fall back to
// reflection if a type is missing here.
var PropKindsByType = map[string][]PropKindEntry{
%s}
`

type entry struct {
	Kind  string
	Field string
	Alt   string
}

type typeInfo struct {
	Name    string
	Entries []entry
}

func main() {
	flag.Parse()
	if flag.NArg() == 0 {
		fmt.Fprintln(os.Stderr, "usage: go run ./script/gen_propkinds.go <pkg-dir>...")
		os.Exit(2)
	}
	for _, dir := range flag.Args() {
		if err := generateForDir(dir); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", dir, err)
			os.Exit(1)
		}
	}
}

func generateForDir(dir string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(f os.FileInfo) bool {
		name := f.Name()
		if strings.HasSuffix(name, "_test.go") {
			return false
		}
		if name == "propkinds_gen.go" {
			return false
		}
		return true
	}, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse: %w", err)
	}
	if len(pkgs) == 0 {
		return fmt.Errorf("no Go package in %s", dir)
	}
	for pkgName, pkg := range pkgs {
		var infos []typeInfo
		for _, f := range pkg.Files {
			ast.Inspect(f, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}
				ents := collect(st)
				if len(ents) == 0 {
					return true
				}
				infos = append(infos, typeInfo{Name: ts.Name.Name, Entries: ents})
				return true
			})
		}
		if len(infos) == 0 {
			continue
		}
		sort.Slice(infos, func(i, j int) bool { return infos[i].Name < infos[j].Name })
		body := renderBody(infos)
		out := fmt.Sprintf(fileHeader, pkgName, body)
		dst := filepath.Join(dir, "propkinds_gen.go")
		if err := writeIfChanged(dst, []byte(out)); err != nil {
			return err
		}
		fmt.Fprintf(os.Stdout, "wrote %s (%d types)\n", dst, len(infos))
	}
	return nil
}

func collect(st *ast.StructType) []entry {
	if st.Fields == nil {
		return nil
	}
	var out []entry
	for _, field := range st.Fields.List {
		if field.Tag == nil || len(field.Names) == 0 {
			continue
		}
		raw := strings.Trim(field.Tag.Value, "`")
		spec, ok := reflect.StructTag(raw).Lookup("payload")
		if !ok {
			continue
		}
		spec = strings.TrimSpace(spec)
		if spec == "" || spec == "-" {
			continue
		}
		parts := strings.Split(spec, ",")
		kind := strings.TrimSpace(parts[0])
		alt := ""
		for _, p := range parts[1:] {
			p = strings.TrimSpace(p)
			if strings.HasPrefix(p, "alt=") {
				alt = strings.TrimPrefix(p, "alt=")
			}
		}
		for _, n := range field.Names {
			if !n.IsExported() {
				continue
			}
			out = append(out, entry{Kind: kind, Field: n.Name, Alt: alt})
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Kind != out[j].Kind {
			return out[i].Kind < out[j].Kind
		}
		return out[i].Field < out[j].Field
	})
	return out
}

func renderBody(infos []typeInfo) string {
	var buf bytes.Buffer
	for _, t := range infos {
		fmt.Fprintf(&buf, "\t%q: {\n", t.Name)
		for _, e := range t.Entries {
			fmt.Fprintf(&buf, "\t\t{Kind: %q, Field: %q, Alt: %q},\n", e.Kind, e.Field, e.Alt)
		}
		buf.WriteString("\t},\n")
	}
	return buf.String()
}

func writeIfChanged(path string, content []byte) error {
	old, err := os.ReadFile(path)
	if err == nil && bytes.Equal(old, content) {
		return nil
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	return nil
}
