// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

//go:build ignore

// generate_matter_schema reads the master matter.js HEAD schema snapshot from
// notes/parity/matter/matter-schema-snapshot.json and emits typed Go constant
// maps under internal/north/matter/schema/:
//
//   - clusters.go  — ClusterRevisions, ClusterNames (map[uint32]uint16/string)
//   - devicetypes.go — DeviceTypeRevisions, DeviceTypeNames
//
// The generated files carry a DO-NOT-EDIT banner and the project SPDX header.
// Run via the Makefile target:
//
//	make generate-matter-schema
//
// Or directly (from the repo root):
//
//	go run ./script/generate_matter_schema.go
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

const (
	snapshotPath    = "notes/parity/matter/matter-schema-snapshot.json"
	schemaDir       = "internal/north/matter/schema"
	clustersFile    = "internal/north/matter/schema/clusters.go"
	devicetypesFile = "internal/north/matter/schema/devicetypes.go"
	provenanceFile  = "internal/north/matter/schema/schema_provenance_gen.go"
)

// snapshotCluster mirrors the cluster shape in matter-schema-snapshot.json.
type snapshotCluster struct {
	ID         uint32 `json:"id"`
	Name       string `json:"name"`
	Revision   uint16 `json:"revision"`
	FeatureMap uint32 `json:"featureMap"`
}

// snapshotDeviceType mirrors the deviceType shape in matter-schema-snapshot.json.
type snapshotDeviceType struct {
	ID       uint32 `json:"id"`
	Name     string `json:"name"`
	Revision uint16 `json:"revision"`
}

// snapshot is the top-level structure of matter-schema-snapshot.json.
type snapshot struct {
	Clusters    []snapshotCluster    `json:"clusters"`
	DeviceTypes []snapshotDeviceType `json:"deviceTypes"`
}

func main() {
	raw, err := os.ReadFile(snapshotPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read %s: %v\n", snapshotPath, err)
		os.Exit(1)
	}

	var snap snapshot
	if err := json.Unmarshal(raw, &snap); err != nil {
		fmt.Fprintf(os.Stderr, "parse %s: %v\n", snapshotPath, err)
		os.Exit(1)
	}

	if len(snap.Clusters) == 0 || len(snap.DeviceTypes) == 0 {
		fmt.Fprintf(os.Stderr, "snapshot appears empty: %d clusters, %d deviceTypes\n",
			len(snap.Clusters), len(snap.DeviceTypes))
		os.Exit(1)
	}

	// Sort for deterministic output.
	sort.Slice(snap.Clusters, func(i, j int) bool {
		return snap.Clusters[i].ID < snap.Clusters[j].ID
	})
	sort.Slice(snap.DeviceTypes, func(i, j int) bool {
		return snap.DeviceTypes[i].ID < snap.DeviceTypes[j].ID
	})

	if err := os.MkdirAll(schemaDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", schemaDir, err)
		os.Exit(1)
	}

	// Compute the SHA-256 of the raw snapshot bytes so the generated
	// provenance file lets tests detect when someone hand-edits a generated
	// constant without re-running the generator.
	sum := sha256.Sum256(raw)
	snapshotSHA256 := hex.EncodeToString(sum[:])

	if err := writeClustersFile(snap.Clusters); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", clustersFile, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d clusters)\n", clustersFile, len(snap.Clusters))

	if err := writeDeviceTypesFile(snap.DeviceTypes); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", devicetypesFile, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d device types)\n", devicetypesFile, len(snap.DeviceTypes))

	if err := writeProvenanceFile(snapshotSHA256); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", provenanceFile, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (SHA-256 %s)\n", provenanceFile, snapshotSHA256)
}

const fileHeaderTpl = `// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/generate_matter_schema.go from
// notes/parity/matter/matter-schema-snapshot.json — DO NOT EDIT.
// Run ` + "`make generate-matter-schema`" + ` to regenerate.

package schema

`

func writeClustersFile(clusters []snapshotCluster) error {
	var buf bytes.Buffer
	buf.WriteString(fileHeaderTpl)

	// ClusterRevisions
	buf.WriteString("// ClusterRevisions maps every cluster ID present in the matter.js HEAD\n")
	buf.WriteString("// schema snapshot to its revision number. Generated from\n")
	buf.WriteString("// notes/parity/matter/matter-schema-snapshot.json.\n")
	buf.WriteString("var ClusterRevisions = map[uint32]uint16{\n")
	for _, c := range clusters {
		fmt.Fprintf(&buf, "\t0x%04X: %d, // %s\n", c.ID, c.Revision, c.Name)
	}
	buf.WriteString("}\n\n")

	// ClusterNames
	buf.WriteString("// ClusterNames maps every cluster ID to its canonical matter.js name.\n")
	buf.WriteString("var ClusterNames = map[uint32]string{\n")
	for _, c := range clusters {
		fmt.Fprintf(&buf, "\t0x%04X: %q,\n", c.ID, c.Name)
	}
	buf.WriteString("}\n")

	return writeIfChanged(clustersFile, buf.Bytes())
}

func writeDeviceTypesFile(dts []snapshotDeviceType) error {
	var buf bytes.Buffer
	buf.WriteString(fileHeaderTpl)

	// DeviceTypeRevisions
	buf.WriteString("// DeviceTypeRevisions maps every device-type ID present in the matter.js\n")
	buf.WriteString("// HEAD schema snapshot to its revision number. Generated from\n")
	buf.WriteString("// notes/parity/matter/matter-schema-snapshot.json.\n")
	buf.WriteString("var DeviceTypeRevisions = map[uint32]uint16{\n")
	for _, dt := range dts {
		fmt.Fprintf(&buf, "\t0x%04X: %d, // %s\n", dt.ID, dt.Revision, dt.Name)
	}
	buf.WriteString("}\n\n")

	// DeviceTypeNames
	buf.WriteString("// DeviceTypeNames maps every device-type ID to its canonical matter.js name.\n")
	buf.WriteString("var DeviceTypeNames = map[uint32]string{\n")
	for _, dt := range dts {
		fmt.Fprintf(&buf, "\t0x%04X: %q,\n", dt.ID, dt.Name)
	}
	buf.WriteString("}\n")

	return writeIfChanged(devicetypesFile, buf.Bytes())
}

func writeProvenanceFile(sha256hex string) error {
	var buf bytes.Buffer
	buf.WriteString(fileHeaderTpl)
	buf.WriteString("// SchemaSnapshotSHA256 is the SHA-256 hex digest of\n")
	buf.WriteString("// notes/parity/matter/matter-schema-snapshot.json at generation time.\n")
	buf.WriteString("// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the\n")
	buf.WriteString("// hash at test time and fails when they diverge — catching hand-edits\n")
	buf.WriteString("// to generated constants that did not go through the generator.\n")
	fmt.Fprintf(&buf, "const SchemaSnapshotSHA256 = %q\n", sha256hex)
	return writeIfChanged(provenanceFile, buf.Bytes())
}

// writeIfChanged writes content to path only when the file content differs,
// keeping file mtimes stable on repeated runs so make does not re-trigger
// dependent steps unnecessarily.
func writeIfChanged(path string, content []byte) error {
	old, err := os.ReadFile(path)
	if err == nil && bytes.Equal(old, content) {
		fmt.Printf("  (unchanged: %s)\n", path)
		return nil
	}
	return os.WriteFile(path, content, 0o644)
}
