// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

//go:build ignore

// generate_schema_digest — compute the canonical digest of the
// north-bound contract assets and write it as a Go constant. Run
// from the repo root (wired into `make export-schemas`):
//
//	go run ./script/generate_schema_digest.go
//
// The digest identifies the exact contract state a daemon binary was
// built from. `GET /api/v1/info` surfaces it as `schema_digest`;
// generated client type packages stamp the same value at generation
// time, which lets a client verify at connect time that its types
// match the daemon build — independent of any human-maintained
// version number. See ADR 0028.
//
// Digest definition (stable, reproducible in any language):
//
//	combined = "<path>\n<sha256-hex of file bytes>\n" for each asset,
//	           paths sorted lexicographically
//	digest   = "sha256:" + sha256-hex(combined)
//
// The contract test TestSchemaDigestFresh recomputes this from the
// repo assets and fails when the generated constant is stale.
package main

import (
	"crypto/sha256"
	"fmt"
	"log"
	"os"
	"sort"
)

// contractAssets is the closed list of files that define the
// north-bound wire contract. Keep in sync with the guard script
// script/check_api_version_bump.sh and the types-package generator.
var contractAssets = []string{
	"assets/openapi.yaml",
	"assets/schemas/enums.json",
	"assets/schemas/types.json",
	"assets/wsapi.json",
}

const outPath = "internal/north/rest/handlers/schema_digest_gen.go"

func main() {
	digest, err := computeDigest(contractAssets)
	if err != nil {
		log.Fatalf("generate_schema_digest: %v", err)
	}
	src := fmt.Sprintf(`// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_schema_digest.go. DO NOT EDIT.

package handlers

// SchemaDigest is the canonical digest of the north-bound contract
// assets (openapi.yaml, wsapi.json, schemas/{enums,types}.json) this
// binary was built from. Served as `+"`schema_digest`"+` by
// `+"`GET /api/v1/info`"+`; generated client type packages carry the
// same value so clients can verify type/daemon parity at connect
// time. See ADR 0028.
const SchemaDigest = %q
`, digest)
	if err := os.WriteFile(outPath, []byte(src), 0o644); err != nil {
		log.Fatalf("generate_schema_digest: write %s: %v", outPath, err)
	}
	fmt.Printf("schema digest %s -> %s\n", digest, outPath)
}

func computeDigest(paths []string) (string, error) {
	sorted := append([]string(nil), paths...)
	sort.Strings(sorted)
	combined := sha256.New()
	for _, p := range sorted {
		data, err := os.ReadFile(p)
		if err != nil {
			return "", fmt.Errorf("read %s: %w", p, err)
		}
		fileSum := sha256.Sum256(data)
		fmt.Fprintf(combined, "%s\n%x\n", p, fileSum)
	}
	return fmt.Sprintf("sha256:%x", combined.Sum(nil)), nil
}
