// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_matter_schema.go from
// notes/parity/matter/matter-schema-snapshot.json — DO NOT EDIT.
// Run `make generate-matter-schema` to regenerate.

package schema

// ClusterRevisions maps every cluster ID present in the matter.js HEAD
// schema snapshot to its revision number. Generated from
// notes/parity/matter/matter-schema-snapshot.json.
var ClusterRevisions = map[uint32]uint16{
	0x0003: 6,  // Identify
	0x0004: 4,  // Groups
	0x0006: 6,  // OnOff
	0x0008: 7,  // LevelControl
	0x001D: 3,  // Descriptor
	0x001E: 1,  // Binding
	0x001F: 3,  // AccessControl
	0x0025: 1,  // Actions
	0x0028: 6,  // BasicInformation
	0x0029: 1,  // OtaSoftwareUpdateProvider
	0x002A: 1,  // OtaSoftwareUpdateRequestor
	0x002B: 1,  // LocalizationConfiguration
	0x002C: 1,  // TimeFormatLocalization
	0x002D: 2,  // UnitLocalization
	0x002E: 1,  // PowerSourceConfiguration
	0x002F: 3,  // PowerSource
	0x0030: 2,  // GeneralCommissioning
	0x0031: 2,  // NetworkCommissioning
	0x0032: 1,  // DiagnosticLogs
	0x0033: 3,  // GeneralDiagnostics
	0x0034: 1,  // SoftwareDiagnostics
	0x0035: 3,  // ThreadNetworkDiagnostics
	0x0036: 1,  // WiFiNetworkDiagnostics
	0x0037: 1,  // EthernetNetworkDiagnostics
	0x0038: 2,  // TimeSynchronization
	0x0039: 6,  // BridgedDeviceBasicInformation
	0x003B: 2,  // Switch
	0x003C: 1,  // AdministratorCommissioning
	0x003E: 2,  // OperationalCredentials
	0x003F: 3,  // GroupKeyManagement
	0x0040: 1,  // FixedLabel
	0x0041: 1,  // UserLabel
	0x0045: 3,  // BooleanState
	0x0046: 3,  // IcdManagement
	0x0048: 2,  // OvenCavityOperationalState
	0x0049: 2,  // OvenMode
	0x004A: 1,  // LaundryDryerControls
	0x0050: 2,  // ModeSelect
	0x0051: 3,  // LaundryWasherMode
	0x0052: 3,  // RefrigeratorAndTemperatureControlledCabinetMode
	0x0053: 2,  // LaundryWasherControls
	0x0054: 4,  // RvcRunMode
	0x0055: 5,  // RvcCleanMode
	0x0056: 1,  // TemperatureControl
	0x0057: 1,  // RefrigeratorAlarm
	0x0059: 3,  // DishwasherMode
	0x005B: 1,  // AirQuality
	0x005C: 2,  // SmokeCoAlarm
	0x005D: 1,  // DishwasherAlarm
	0x005E: 2,  // MicrowaveOvenMode
	0x005F: 1,  // MicrowaveOvenControl
	0x0060: 3,  // OperationalState
	0x0061: 3,  // RvcOperationalState
	0x0062: 1,  // ScenesManagement
	0x0064: 1,  // TemperatureAlarm
	0x0065: 1,  // Groupcast
	0x0071: 1,  // HepaFilterMonitoring
	0x0072: 1,  // ActivatedCarbonFilterMonitoring
	0x0079: 1,  // WaterTankLevelMonitoring
	0x0080: 2,  // BooleanStateConfiguration
	0x0081: 1,  // ValveConfigurationAndControl
	0x0090: 3,  // ElectricalPowerMeasurement
	0x0091: 2,  // ElectricalEnergyMeasurement
	0x0094: 2,  // WaterHeaterManagement
	0x0095: 4,  // CommodityPrice
	0x0097: 3,  // Messages
	0x0098: 4,  // DeviceEnergyManagement
	0x0099: 4,  // EnergyEvse
	0x009B: 1,  // EnergyPreference
	0x009C: 1,  // PowerTopology
	0x009D: 2,  // EnergyEvseMode
	0x009E: 1,  // WaterHeaterMode
	0x009F: 2,  // DeviceEnergyManagementMode
	0x00A0: 1,  // ElectricalGridConditions
	0x0101: 10, // DoorLock
	0x0102: 8,  // WindowCovering
	0x0104: 1,  // ClosureControl
	0x0105: 1,  // ClosureDimension
	0x0150: 2,  // ServiceArea
	0x0200: 5,  // PumpConfigurationAndControl
	0x0201: 11, // Thermostat
	0x0202: 6,  // FanControl
	0x0204: 2,  // ThermostatUserInterfaceConfiguration
	0x0300: 9,  // ColorControl
	0x0400: 5,  // IlluminanceMeasurement
	0x0402: 6,  // TemperatureMeasurement
	0x0403: 5,  // PressureMeasurement
	0x0404: 5,  // FlowMeasurement
	0x0405: 5,  // RelativeHumidityMeasurement
	0x0406: 7,  // OccupancySensing
	0x040C: 5,  // CarbonMonoxideConcentrationMeasurement
	0x040D: 5,  // CarbonDioxideConcentrationMeasurement
	0x0413: 5,  // NitrogenDioxideConcentrationMeasurement
	0x0415: 5,  // OzoneConcentrationMeasurement
	0x042A: 5,  // Pm25ConcentrationMeasurement
	0x042B: 5,  // FormaldehydeConcentrationMeasurement
	0x042C: 5,  // Pm1ConcentrationMeasurement
	0x042D: 5,  // Pm10ConcentrationMeasurement
	0x042E: 5,  // TotalVolatileOrganicCompoundsConcentrationMeasurement
	0x042F: 5,  // RadonConcentrationMeasurement
	0x0430: 1,  // SoilMeasurement
	0x0431: 1,  // AmbientContextSensing
	0x0451: 1,  // WiFiNetworkManagement
	0x0452: 1,  // ThreadBorderRouterManagement
	0x0453: 1,  // ThreadNetworkDirectory
	0x0503: 1,  // WakeOnLan
	0x0504: 2,  // Channel
	0x0505: 2,  // TargetNavigator
	0x0506: 2,  // MediaPlayback
	0x0507: 1,  // MediaInput
	0x0508: 1,  // LowPower
	0x0509: 1,  // KeypadInput
	0x050A: 2,  // ContentLauncher
	0x050B: 1,  // AudioOutput
	0x050C: 2,  // ApplicationLauncher
	0x050D: 1,  // ApplicationBasic
	0x050E: 2,  // AccountLogin
	0x050F: 1,  // ContentControl
	0x0510: 1,  // ContentAppObserver
	0x0550: 1,  // ZoneManagement
	0x0551: 2,  // CameraAvStreamManagement
	0x0552: 1,  // CameraAvSettingsUserLevelManagement
	0x0553: 2,  // WebRtcTransportProvider
	0x0554: 2,  // WebRtcTransportRequestor
	0x0555: 2,  // PushAvStreamTransport
	0x0556: 2,  // Chime
	0x0700: 1,  // CommodityTariff
	0x0750: 1,  // EcosystemInformation
	0x0751: 1,  // CommissionerControl
	0x0752: 1,  // JointFabricDatastore
	0x0753: 1,  // JointFabricAdministrator
	0x0801: 1,  // TlsCertificateManagement
	0x0802: 1,  // TlsClientManagement
	0x0B06: 1,  // MeterIdentification
	0x0B07: 1,  // CommodityMetering
}

// ClusterNames maps every cluster ID to its canonical matter.js name.
var ClusterNames = map[uint32]string{
	0x0003: "Identify",
	0x0004: "Groups",
	0x0006: "OnOff",
	0x0008: "LevelControl",
	0x001D: "Descriptor",
	0x001E: "Binding",
	0x001F: "AccessControl",
	0x0025: "Actions",
	0x0028: "BasicInformation",
	0x0029: "OtaSoftwareUpdateProvider",
	0x002A: "OtaSoftwareUpdateRequestor",
	0x002B: "LocalizationConfiguration",
	0x002C: "TimeFormatLocalization",
	0x002D: "UnitLocalization",
	0x002E: "PowerSourceConfiguration",
	0x002F: "PowerSource",
	0x0030: "GeneralCommissioning",
	0x0031: "NetworkCommissioning",
	0x0032: "DiagnosticLogs",
	0x0033: "GeneralDiagnostics",
	0x0034: "SoftwareDiagnostics",
	0x0035: "ThreadNetworkDiagnostics",
	0x0036: "WiFiNetworkDiagnostics",
	0x0037: "EthernetNetworkDiagnostics",
	0x0038: "TimeSynchronization",
	0x0039: "BridgedDeviceBasicInformation",
	0x003B: "Switch",
	0x003C: "AdministratorCommissioning",
	0x003E: "OperationalCredentials",
	0x003F: "GroupKeyManagement",
	0x0040: "FixedLabel",
	0x0041: "UserLabel",
	0x0045: "BooleanState",
	0x0046: "IcdManagement",
	0x0048: "OvenCavityOperationalState",
	0x0049: "OvenMode",
	0x004A: "LaundryDryerControls",
	0x0050: "ModeSelect",
	0x0051: "LaundryWasherMode",
	0x0052: "RefrigeratorAndTemperatureControlledCabinetMode",
	0x0053: "LaundryWasherControls",
	0x0054: "RvcRunMode",
	0x0055: "RvcCleanMode",
	0x0056: "TemperatureControl",
	0x0057: "RefrigeratorAlarm",
	0x0059: "DishwasherMode",
	0x005B: "AirQuality",
	0x005C: "SmokeCoAlarm",
	0x005D: "DishwasherAlarm",
	0x005E: "MicrowaveOvenMode",
	0x005F: "MicrowaveOvenControl",
	0x0060: "OperationalState",
	0x0061: "RvcOperationalState",
	0x0062: "ScenesManagement",
	0x0064: "TemperatureAlarm",
	0x0065: "Groupcast",
	0x0071: "HepaFilterMonitoring",
	0x0072: "ActivatedCarbonFilterMonitoring",
	0x0079: "WaterTankLevelMonitoring",
	0x0080: "BooleanStateConfiguration",
	0x0081: "ValveConfigurationAndControl",
	0x0090: "ElectricalPowerMeasurement",
	0x0091: "ElectricalEnergyMeasurement",
	0x0094: "WaterHeaterManagement",
	0x0095: "CommodityPrice",
	0x0097: "Messages",
	0x0098: "DeviceEnergyManagement",
	0x0099: "EnergyEvse",
	0x009B: "EnergyPreference",
	0x009C: "PowerTopology",
	0x009D: "EnergyEvseMode",
	0x009E: "WaterHeaterMode",
	0x009F: "DeviceEnergyManagementMode",
	0x00A0: "ElectricalGridConditions",
	0x0101: "DoorLock",
	0x0102: "WindowCovering",
	0x0104: "ClosureControl",
	0x0105: "ClosureDimension",
	0x0150: "ServiceArea",
	0x0200: "PumpConfigurationAndControl",
	0x0201: "Thermostat",
	0x0202: "FanControl",
	0x0204: "ThermostatUserInterfaceConfiguration",
	0x0300: "ColorControl",
	0x0400: "IlluminanceMeasurement",
	0x0402: "TemperatureMeasurement",
	0x0403: "PressureMeasurement",
	0x0404: "FlowMeasurement",
	0x0405: "RelativeHumidityMeasurement",
	0x0406: "OccupancySensing",
	0x040C: "CarbonMonoxideConcentrationMeasurement",
	0x040D: "CarbonDioxideConcentrationMeasurement",
	0x0413: "NitrogenDioxideConcentrationMeasurement",
	0x0415: "OzoneConcentrationMeasurement",
	0x042A: "Pm25ConcentrationMeasurement",
	0x042B: "FormaldehydeConcentrationMeasurement",
	0x042C: "Pm1ConcentrationMeasurement",
	0x042D: "Pm10ConcentrationMeasurement",
	0x042E: "TotalVolatileOrganicCompoundsConcentrationMeasurement",
	0x042F: "RadonConcentrationMeasurement",
	0x0430: "SoilMeasurement",
	0x0431: "AmbientContextSensing",
	0x0451: "WiFiNetworkManagement",
	0x0452: "ThreadBorderRouterManagement",
	0x0453: "ThreadNetworkDirectory",
	0x0503: "WakeOnLan",
	0x0504: "Channel",
	0x0505: "TargetNavigator",
	0x0506: "MediaPlayback",
	0x0507: "MediaInput",
	0x0508: "LowPower",
	0x0509: "KeypadInput",
	0x050A: "ContentLauncher",
	0x050B: "AudioOutput",
	0x050C: "ApplicationLauncher",
	0x050D: "ApplicationBasic",
	0x050E: "AccountLogin",
	0x050F: "ContentControl",
	0x0510: "ContentAppObserver",
	0x0550: "ZoneManagement",
	0x0551: "CameraAvStreamManagement",
	0x0552: "CameraAvSettingsUserLevelManagement",
	0x0553: "WebRtcTransportProvider",
	0x0554: "WebRtcTransportRequestor",
	0x0555: "PushAvStreamTransport",
	0x0556: "Chime",
	0x0700: "CommodityTariff",
	0x0750: "EcosystemInformation",
	0x0751: "CommissionerControl",
	0x0752: "JointFabricDatastore",
	0x0753: "JointFabricAdministrator",
	0x0801: "TlsCertificateManagement",
	0x0802: "TlsClientManagement",
	0x0B06: "MeterIdentification",
	0x0B07: "CommodityMetering",
}
