// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_matter_schema.go from
// notes/parity/matter/matter-schema-snapshot.json — DO NOT EDIT.
// Run `make generate-matter-schema` to regenerate.

package schema

// DeviceTypeRevisions maps every device-type ID present in the matter.js
// HEAD schema snapshot to its revision number. Generated from
// notes/parity/matter/matter-schema-snapshot.json.
var DeviceTypeRevisions = map[uint32]uint16{
	0x000A: 4, // DoorLock
	0x000B: 3, // DoorLockController
	0x000E: 2, // Aggregator
	0x000F: 3, // GenericSwitch
	0x0011: 1, // PowerSource
	0x0012: 1, // OtaRequestor
	0x0013: 3, // BridgedNode
	0x0014: 1, // OtaProvider
	0x0015: 2, // ContactSensor
	0x0016: 4, // RootNode
	0x0017: 1, // SolarPower
	0x0018: 2, // BatteryStorage
	0x0019: 1, // SecondaryNetworkInterface
	0x0022: 1, // Speaker
	0x0023: 2, // CastingVideoPlayer
	0x0024: 2, // ContentApp
	0x0027: 1, // ModeSelect
	0x0028: 2, // BasicVideoPlayer
	0x0029: 2, // CastingVideoClient
	0x002A: 2, // VideoRemoteControl
	0x002B: 4, // Fan
	0x002C: 1, // AirQualitySensor
	0x002D: 2, // AirPurifier
	0x0040: 1, // IrrigationSystem
	0x0041: 2, // WaterFreezeDetector
	0x0042: 1, // WaterValve
	0x0043: 2, // WaterLeakDetector
	0x0044: 2, // RainSensor
	0x0045: 1, // SoilSensor
	0x0070: 3, // Refrigerator
	0x0071: 6, // TemperatureControlledCabinet
	0x0072: 3, // RoomAirConditioner
	0x0073: 2, // LaundryWasher
	0x0074: 4, // RoboticVacuumCleaner
	0x0075: 2, // Dishwasher
	0x0076: 1, // SmokeCoAlarm
	0x0077: 2, // CookSurface
	0x0078: 1, // Cooktop
	0x0079: 2, // MicrowaveOven
	0x007A: 1, // ExtractorHood
	0x007B: 2, // Oven
	0x007C: 2, // LaundryDryer
	0x0090: 2, // NetworkInfrastructureManager
	0x0091: 2, // ThreadBorderRouter
	0x0100: 3, // OnOffLight
	0x0101: 3, // DimmableLight
	0x0103: 3, // OnOffLightSwitch
	0x0104: 3, // DimmerSwitch
	0x0105: 3, // ColorDimmerSwitch
	0x0106: 4, // LightSensor
	0x0107: 4, // OccupancySensor
	0x010A: 4, // OnOffPlugInUnit
	0x010B: 5, // DimmablePlugInUnit
	0x010C: 4, // ColorTemperatureLight
	0x010D: 4, // ExtendedColorLight
	0x010F: 2, // MountedOnOffControl
	0x0110: 2, // MountedDimmableLoadControl
	0x0130: 1, // JointFabricAdministrator
	0x0140: 2, // Intercom
	0x0141: 2, // AudioDoorbell
	0x0142: 1, // Camera
	0x0143: 1, // VideoDoorbell
	0x0144: 1, // FloodlightCamera
	0x0145: 1, // SnapshotCamera
	0x0146: 1, // Chime
	0x0147: 1, // CameraController
	0x0148: 2, // Doorbell
	0x0202: 6, // WindowCovering
	0x0203: 4, // WindowCoveringController
	0x0230: 1, // Closure
	0x0231: 1, // ClosurePanel
	0x023E: 1, // ClosureController
	0x0301: 6, // Thermostat
	0x0302: 3, // TemperatureSensor
	0x0303: 3, // Pump
	0x0304: 4, // PumpController
	0x0305: 3, // PressureSensor
	0x0306: 3, // FlowSensor
	0x0307: 3, // HumiditySensor
	0x0309: 1, // HeatPump
	0x030A: 1, // ThermostatController
	0x050C: 2, // EnergyEvse
	0x050D: 3, // DeviceEnergyManagement
	0x050F: 1, // WaterHeater
	0x0510: 1, // ElectricalSensor
	0x0511: 1, // ElectricalUtilityMeter
	0x0512: 1, // MeterReferencePoint
	0x0513: 1, // ElectricalEnergyTariff
	0x0514: 1, // ElectricalMeter
	0x0840: 3, // ControlBridge
	0x0850: 3, // OnOffSensor
}

// DeviceTypeNames maps every device-type ID to its canonical matter.js name.
var DeviceTypeNames = map[uint32]string{
	0x000A: "DoorLock",
	0x000B: "DoorLockController",
	0x000E: "Aggregator",
	0x000F: "GenericSwitch",
	0x0011: "PowerSource",
	0x0012: "OtaRequestor",
	0x0013: "BridgedNode",
	0x0014: "OtaProvider",
	0x0015: "ContactSensor",
	0x0016: "RootNode",
	0x0017: "SolarPower",
	0x0018: "BatteryStorage",
	0x0019: "SecondaryNetworkInterface",
	0x0022: "Speaker",
	0x0023: "CastingVideoPlayer",
	0x0024: "ContentApp",
	0x0027: "ModeSelect",
	0x0028: "BasicVideoPlayer",
	0x0029: "CastingVideoClient",
	0x002A: "VideoRemoteControl",
	0x002B: "Fan",
	0x002C: "AirQualitySensor",
	0x002D: "AirPurifier",
	0x0040: "IrrigationSystem",
	0x0041: "WaterFreezeDetector",
	0x0042: "WaterValve",
	0x0043: "WaterLeakDetector",
	0x0044: "RainSensor",
	0x0045: "SoilSensor",
	0x0070: "Refrigerator",
	0x0071: "TemperatureControlledCabinet",
	0x0072: "RoomAirConditioner",
	0x0073: "LaundryWasher",
	0x0074: "RoboticVacuumCleaner",
	0x0075: "Dishwasher",
	0x0076: "SmokeCoAlarm",
	0x0077: "CookSurface",
	0x0078: "Cooktop",
	0x0079: "MicrowaveOven",
	0x007A: "ExtractorHood",
	0x007B: "Oven",
	0x007C: "LaundryDryer",
	0x0090: "NetworkInfrastructureManager",
	0x0091: "ThreadBorderRouter",
	0x0100: "OnOffLight",
	0x0101: "DimmableLight",
	0x0103: "OnOffLightSwitch",
	0x0104: "DimmerSwitch",
	0x0105: "ColorDimmerSwitch",
	0x0106: "LightSensor",
	0x0107: "OccupancySensor",
	0x010A: "OnOffPlugInUnit",
	0x010B: "DimmablePlugInUnit",
	0x010C: "ColorTemperatureLight",
	0x010D: "ExtendedColorLight",
	0x010F: "MountedOnOffControl",
	0x0110: "MountedDimmableLoadControl",
	0x0130: "JointFabricAdministrator",
	0x0140: "Intercom",
	0x0141: "AudioDoorbell",
	0x0142: "Camera",
	0x0143: "VideoDoorbell",
	0x0144: "FloodlightCamera",
	0x0145: "SnapshotCamera",
	0x0146: "Chime",
	0x0147: "CameraController",
	0x0148: "Doorbell",
	0x0202: "WindowCovering",
	0x0203: "WindowCoveringController",
	0x0230: "Closure",
	0x0231: "ClosurePanel",
	0x023E: "ClosureController",
	0x0301: "Thermostat",
	0x0302: "TemperatureSensor",
	0x0303: "Pump",
	0x0304: "PumpController",
	0x0305: "PressureSensor",
	0x0306: "FlowSensor",
	0x0307: "HumiditySensor",
	0x0309: "HeatPump",
	0x030A: "ThermostatController",
	0x050C: "EnergyEvse",
	0x050D: "DeviceEnergyManagement",
	0x050F: "WaterHeater",
	0x0510: "ElectricalSensor",
	0x0511: "ElectricalUtilityMeter",
	0x0512: "MeterReferencePoint",
	0x0513: "ElectricalEnergyTariff",
	0x0514: "ElectricalMeter",
	0x0840: "ControlBridge",
	0x0850: "OnOffSensor",
}
