// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

// Code generated by script/generate_matter_schema.go from
// docs/parity/matter/matter-schema-snapshot.json — DO NOT EDIT.
// Run `make generate-matter-schema` to regenerate.

package schema

// SchemaSnapshotSHA256 is the SHA-256 hex digest of
// docs/parity/matter/matter-schema-snapshot.json at generation time.
// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the
// hash at test time and fails when they diverge — catching hand-edits
// to generated constants that did not go through the generator.
const SchemaSnapshotSHA256 = "560f23a6d0f327d7b3f9d6c64db26d12777b386cde7bd945d240ed6426e7dc06"
