// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

// Code generated by script/generate_matter_schema.go from
// notes/parity/matter/matter-schema-snapshot.json — DO NOT EDIT.
// Run `make generate-matter-schema` to regenerate.

package schema

// SchemaSnapshotSHA256 is the SHA-256 hex digest of
// notes/parity/matter/matter-schema-snapshot.json at generation time.
// The TestMatterSchemaSnapshotHashMatchesEmbedded test recomputes the
// hash at test time and fails when they diverge — catching hand-edits
// to generated constants that did not go through the generator.
const SchemaSnapshotSHA256 = "c714c4b3bd41156c07099208dafd92ad2357f0e03379f8ada6b42e05dac38add"
