// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.
//
// The Home Assistant entity-description table behind the MQTT discovery
// plane. [HARegistryDescriptionLookup] returns the canonical description
// for a (category, parameter, model, unit, postfix, varName) tuple, and
// applyEntityDescription / applyEntityDescriptionStrict write its fields
// into the discovery payload: device_class, state_class, entity_category,
// icon, translation_key, unit_of_measurement, suggested_display_precision,
// enabled_by_default, options, plus the per-number multiplier the caller
// applies against the live value.
//
// This table is maintained here, by hand, like every other device-facing
// catalogue in this repository (ADR 0063). It is not generated, and the
// wire semantics behind each rule are recorded in
// notes/reference/ha-entity-description-table.md rather than in this file
// — ADR 0067 draws the line this table sits on, and the repository's
// comment rules keep provenance out of Go comments.

package mqtt

import "strings"

// HARegistryDescription is the wire-relevant subset of one entity
// description. A pointer field denotes an optional value: nil means "not
// set", which leaves Home Assistant's own default in place.
type HARegistryDescription struct {
	Key                       string
	DeviceClass               string
	StateClass                string
	EntityCategory            string
	Icon                      string
	TranslationKey            string
	UnitOfMeasurement         string
	SuggestedDisplayPrecision *int
	EnabledByDefault          *bool // nil = HA default (true)
	Options                   []string
	NameSource                string
	Multiplier                *float64 // nil = no override
}

// HARegistryDescriptionRule is one entry in the priority-sorted rule
// list. Matching is "every specified criterion must match"; an empty
// criterion matches anything.
//
// VarNameContains is matched against the caller-supplied varName, which
// every production call site currently leaves empty — a rule that sets it
// therefore cannot fire until a call site passes a name. The rules that
// carry one are listed in notes/reference/ha-entity-description-table.md.
type HARegistryDescriptionRule struct {
	Description     HARegistryDescription
	Category        string
	Parameters      []string // nil = match any
	Devices         []string // nil = match any (case-insensitive prefix)
	Unit            string   // "" = match any
	Postfix         string   // "" = match any
	VarNameContains string   // "" = match any
	Priority        int
}

func entityIntPtr(v int) *int             { return &v }
func entityFloat64Ptr(v float64) *float64 { return &v }
func entityBoolPtr(v bool) *bool          { return &v }

func paramListContains(list []string, parameter string) bool {
	if len(list) == 0 {
		return true
	}
	for _, p := range list {
		if strings.EqualFold(p, parameter) {
			return true
		}
	}
	return false
}

func deviceListMatches(list []string, model string) bool {
	if len(list) == 0 {
		return true
	}
	low := strings.ToLower(model)
	for _, d := range list {
		if strings.HasPrefix(low, strings.ToLower(d)) {
			return true
		}
	}
	return false
}

func varNameMatches(needle, haystack string) bool {
	if needle == "" {
		return true
	}
	return strings.Contains(strings.ToLower(haystack), strings.ToLower(needle))
}

// HARegistryDescriptionLookup returns the canonical description for the
// given matching criteria. Returns the first matching rule (rules
// are pre-sorted by descending priority); falls back to the
// per-category default (`haRegistryDescriptionDefaults`); finally returns nil
// when neither produces a match.
//
// Empty strings disable that criterion. Pass the wire `parameter`
// in upper case (matches the rule literals; the helper case-folds).
func HARegistryDescriptionLookup(category, parameter, model, unit, postfix, varName string) *HARegistryDescription {
	if category == "" {
		return nil
	}
	for i := range haRegistryDescriptionRules {
		r := &haRegistryDescriptionRules[i]
		if r.Category != category {
			continue
		}
		if !paramListContains(r.Parameters, parameter) {
			continue
		}
		if !deviceListMatches(r.Devices, model) {
			continue
		}
		if r.Unit != "" && r.Unit != unit {
			continue
		}
		if r.Postfix != "" && !strings.EqualFold(r.Postfix, postfix) {
			continue
		}
		if !varNameMatches(r.VarNameContains, varName) {
			continue
		}
		d := r.Description
		return &d
	}
	if def, ok := haRegistryDescriptionDefaults[category]; ok {
		return &def
	}
	return nil
}

// haRegistryDescriptionRules is the priority-sorted rule list. Its
// content is pinned by TestHARegistryDescriptionRulesMatchTheGolden
// against tests/contract/testdata/ha_registry_description_rules.json.
var haRegistryDescriptionRules = []HARegistryDescriptionRule{
	{Description: HARegistryDescription{Key: "INTRUSION_ALARM", DeviceClass: "safety", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"INTRUSION_ALARM"}, Devices: []string{"HmIP-SWSD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SMOKE_ALARM", DeviceClass: "smoke", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"SMOKE_ALARM"}, Devices: []string{"HmIP-SWSD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "door", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HmIP-DLP"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "occupancy", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HmIP-DSD-PCB"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "opening", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HmIP-SCI", "HmIP-FCI1", "HmIP-FCI6"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "smoke", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HM-Sec-SD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "window", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HmIP-SWDO", "HmIP-SWDM", "HM-Sec-SC", "HM-SCI-3-FM", "ZEL STG RM FFK"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "moisture", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"STATE"}, Devices: []string{"HM-Sen-RD-O"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "WINDOW_OPEN", DeviceClass: "window", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"WINDOW_OPEN"}, Devices: []string{"HmIP-SRH", "HM-Sec-RHS"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "WORKING", DeviceClass: "running", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"WORKING"}, Devices: []string{"HM-Sec-Win"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "FREQUENCY", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "frequency", UnitOfMeasurement: "mHz", NameSource: "parameter"}, Category: "number", Parameters: []string{"FREQUENCY"}, Devices: []string{"HMW-IO-12-Sw14-DR"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "pipe_level", UnitOfMeasurement: "%", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "number", Parameters: []string{"LEVEL"}, Devices: []string{"HmIP-eTRV", "HmIP-HEATING"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "ACTUAL_TEMPERATURE", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "°C", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ACTUAL_TEMPERATURE"}, Devices: []string{"ELV-SH-BS", "HmIP-BB", "HmIP-BD", "HmIP-BR", "HmIP-BS", "HmIP-DR", "HmIP-FB", "HmIP-FD", "HmIP-FR", "HmIP-FS", "HmIP-MOD-OC8", "HmIP-PCB", "HmIP-PD", "HmIP-PS", "HmIP-USB", "HmIPW-DR", "HmIPW-FIO"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "COLOR", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"COLOR"}, Devices: []string{"HmIP-BSL", "HmIP-RGBW", "HmIPW-WRC6"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "FREQUENCY", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "frequency", UnitOfMeasurement: "mHz", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"FREQUENCY"}, Devices: []string{"HMW-IO-12-Sw14-DR"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "pipe_level", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "sensor", Parameters: []string{"LEVEL"}, Devices: []string{"HmIP-eTRV", "HmIP-HEATING", "HmIP-FALMOT-C12", "HmIPW-FALMOT-C12"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "cover_level", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "sensor", Parameters: []string{"LEVEL"}, Devices: []string{"HmIP-BROLL", "HmIP-FROLL", "HmIP-BBL", "HmIP-DRBLI4", "HmIPW-DRBL4", "HmIP-FBL"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "light_level", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "sensor", Parameters: []string{"LEVEL"}, Devices: []string{"HmIP-BSL", "HmIP-BDT", "HmIP-DRDI3", "HmIP-FDT", "HmIPW-PDT", "HmIP-RGBW", "HmIP-SCTH230", "HmIPW-DRD3", "HmIPW-WRC6"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "cover_tilt", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "sensor", Parameters: []string{"LEVEL_2"}, Devices: []string{"HmIP-BBL", "HmIP-DRBLI4", "HmIPW-DRBL4", "HmIP-FBL"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SEC-KEY_DIRECTION", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_direction", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DIRECTION"}, Devices: []string{"HM-Sec-Key"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SEC-KEY_ERROR", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_key_error", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ERROR"}, Devices: []string{"HM-Sec-Key"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SEC-WIN_DIRECTION", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_direction", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DIRECTION"}, Devices: []string{"HM-Sec-Win"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SEC-WIN_ERROR", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_win_error", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ERROR"}, Devices: []string{"HM-Sec-Win"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "SEC-WIN_STATUS", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_win_status", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"STATUS"}, Devices: []string{"HM-Sec-Win"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "STATE", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "sec_wds_state", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"STATE"}, Devices: []string{"HM-Sec-WDS"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "TIME_OF_OPERATION", DeviceClass: "duration", StateClass: "total_increasing", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "d", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter", Multiplier: entityFloat64Ptr(1.1574074074074073e-05)}, Category: "sensor", Parameters: []string{"TIME_OF_OPERATION"}, Devices: []string{"HmIP-SWSD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "TRI_STATE", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "tri_state", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"STATE"}, Devices: []string{"HmIP-SRH", "HmIP-STV", "HM-Sec-RHS", "HM-Sec-xx", "ZEL STG RM FDK"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "VALVE_STATE", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "pipe_level", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"VALVE_STATE"}, Devices: []string{"HM-CC-RT-DN", "HM-CC-VD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "WKP_CODE_STATE", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "wkp_code_state", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"CODE_STATE"}, Devices: []string{"HmIP-WKP"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 10},
	{Description: HARegistryDescription{Key: "ACOUSTIC_ALARM_ACTIVE", DeviceClass: "safety", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"ACOUSTIC_ALARM_ACTIVE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "ALARMSTATE", DeviceClass: "safety", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"ALARMSTATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "BLOCKED", DeviceClass: "problem", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"BLOCKED_PERMANENT", "BLOCKED_TEMPORARY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "BURST_LIMIT_WARNING", DeviceClass: "problem", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"BURST_LIMIT_WARNING"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DEW_POINT_ALARM", DeviceClass: "problem", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"DEW_POINT_ALARM"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DUTY_CYCLE", DeviceClass: "problem", EntityCategory: "diagnostic", Icon: "mdi:radio-tower", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"DUTYCYCLE", "DUTY_CYCLE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "EMERGENCY_OPERATION", DeviceClass: "safety", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"EMERGENCY_OPERATION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "ERROR_JAMMED", DeviceClass: "problem", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"ERROR_JAMMED"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "HEATER_STATE", DeviceClass: "heat", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"HEATER_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "LOW_BAT", DeviceClass: "battery", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"LOWBAT", "LOW_BAT", "LOWBAT_SENSOR"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MOISTURE_DETECTED", DeviceClass: "moisture", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"MOISTURE_DETECTED"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MOTION", DeviceClass: "motion", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"MOTION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "OPTICAL_ALARM_ACTIVE", DeviceClass: "safety", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"OPTICAL_ALARM_ACTIVE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "POWER_MAINS_FAILURE", DeviceClass: "power", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"POWER_MAINS_FAILURE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "PRESENCE_DETECTION_STATE", DeviceClass: "presence", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"PRESENCE_DETECTION_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "PROCESS", DeviceClass: "running", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"PROCESS", "WORKING"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "RAINING", DeviceClass: "moisture", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"RAINING"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SABOTAGE", DeviceClass: "tamper", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"SABOTAGE", "SABOTAGE_STICKY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SABOTAGE", DeviceClass: "tamper", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"SABOTAGE_ACCELERATION", "SABOTAGE_BATTERY", "SABOTAGE_MAGNETIC_FIELD", "SABOTAGE_VERTICAL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WATERLEVEL_DETECTED", DeviceClass: "moisture", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"WATERLEVEL_DETECTED"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WINDOW_STATE", DeviceClass: "window", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "binary_sensor", Parameters: []string{"WINDOW_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "PRESS_LONG", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "button", Parameters: []string{"PRESS_LONG"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "PRESS_SHORT", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "button", Parameters: []string{"PRESS_SHORT"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "RESET_MOTION", DeviceClass: "", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "button", Parameters: []string{"RESET_MOTION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "RESET_PRESENCE", DeviceClass: "", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "button", Parameters: []string{"RESET_PRESENCE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "BLIND", DeviceClass: "blind", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "cover", Parameters: nil, Devices: []string{"HmIP-BBL", "HmIP-FBL", "HmIP-DRBLI4", "HmIPW-DRBL4"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "GARAGE-HO", DeviceClass: "garage", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "cover", Parameters: nil, Devices: []string{"HmIP-MOD-HO", "HmIP-MOD-TM"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "HM-Sec-Win", DeviceClass: "window", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "cover", Parameters: nil, Devices: []string{"HM-Sec-Win"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "HmIP-HDM1", DeviceClass: "shade", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "cover", Parameters: nil, Devices: []string{"HmIP-HDM1"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SHUTTER", DeviceClass: "shutter", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "cover", Parameters: nil, Devices: []string{"HmIP-BROLL", "HmIP-FROLL", "HM-LC-Bl1PBU-FM"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CONNECTIVITY_SENSOR", DeviceClass: "connectivity", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "hub_binary_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "Connectivity", Priority: 0},
	{Description: HARegistryDescription{Key: "INSTALL_MODE_BIDCOS_BUTTON", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "install_mode_bidcos_button", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "hub_button", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "INSTALL_MODE_BIDCOS_BUTTON", Priority: 0},
	{Description: HARegistryDescription{Key: "INSTALL_MODE_HMIP_BUTTON", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "install_mode_hmip_button", UnitOfMeasurement: "", NameSource: "parameter"}, Category: "hub_button", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "INSTALL_MODE_HMIP_BUTTON", Priority: 0},
	{Description: HARegistryDescription{Key: "ALARM_MESSAGES", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "alarm_messages", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "ALARM_MESSAGES", Priority: 0},
	{Description: HARegistryDescription{Key: "CONNECTION_LATENCY", DeviceClass: "duration", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "mdi:timer-outline", TranslationKey: "connection_latency", UnitOfMeasurement: "ms", SuggestedDisplayPrecision: entityIntPtr(1), NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "connection_latency", Priority: 0},
	{Description: HARegistryDescription{Key: "ENERGY_COUNTER", DeviceClass: "energy", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "energy_counter_total", UnitOfMeasurement: "Wh", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svEnergyCounter", Priority: 0},
	{Description: HARegistryDescription{Key: "ENERGY_COUNTER_FEED_IN", DeviceClass: "energy", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "energy_counter_feed_in_total", UnitOfMeasurement: "Wh", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svEnergyCounterFeedIn", Priority: 0},
	{Description: HARegistryDescription{Key: "INBOX", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "inbox", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "inbox", Priority: 0},
	{Description: HARegistryDescription{Key: "INSTALL_MODE_BIDCOS", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "install_mode_bidcos", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "INSTALL_MODE_BIDCOS", Priority: 0},
	{Description: HARegistryDescription{Key: "INSTALL_MODE_HMIP", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "install_mode_hmip", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "INSTALL_MODE_HMIP", Priority: 0},
	{Description: HARegistryDescription{Key: "LAST_EVENT_AGE", DeviceClass: "duration", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "mdi:clock-alert-outline", TranslationKey: "last_event_age", UnitOfMeasurement: "s", SuggestedDisplayPrecision: entityIntPtr(1), NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "last_event_age", Priority: 0},
	{Description: HARegistryDescription{Key: "RAIN_COUNTER", DeviceClass: "", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "rain_counter_total", UnitOfMeasurement: "mm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPRainCounter", Priority: 0},
	{Description: HARegistryDescription{Key: "RAIN_COUNTER_TODAY", DeviceClass: "", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "rain_counter_today", UnitOfMeasurement: "mm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPRainCounterToday", Priority: 0},
	{Description: HARegistryDescription{Key: "RAIN_COUNTER_YESTERDAY", DeviceClass: "", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "rain_counter_yesterday", UnitOfMeasurement: "mm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPRainCounterYesterday", Priority: 0},
	{Description: HARegistryDescription{Key: "SERVICE_MESSAGES", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "service_messages", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "SERVICE_MESSAGES", Priority: 0},
	{Description: HARegistryDescription{Key: "SUNSHINE_COUNTER", DeviceClass: "duration", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "sunshine_counter_total", UnitOfMeasurement: "min", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPSunshineCounter", Priority: 0},
	{Description: HARegistryDescription{Key: "SUNSHINE_COUNTER_TODAY", DeviceClass: "duration", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "sunshine_counter_today", UnitOfMeasurement: "min", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPSunshineCounterToday", Priority: 0},
	{Description: HARegistryDescription{Key: "SUNSHINE_COUNTER_YESTERDAY", DeviceClass: "duration", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "sunshine_counter_yesterday", UnitOfMeasurement: "min", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "svHmIPSunshineCounterYesterday", Priority: 0},
	{Description: HARegistryDescription{Key: "SYSTEM_HEALTH", DeviceClass: "", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "mdi:heart-pulse", TranslationKey: "system_health", UnitOfMeasurement: "%", SuggestedDisplayPrecision: entityIntPtr(1), NameSource: "parameter"}, Category: "hub_sensor", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "system_health", Priority: 0},
	{Description: HARegistryDescription{Key: "BUTTON_LOCK", DeviceClass: "", EntityCategory: "config", Icon: "", TranslationKey: "button_lock", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "lock", Parameters: nil, Devices: nil, Unit: "", Postfix: "BUTTON_LOCK", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "FREQUENCY", DeviceClass: "frequency", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "Hz", NameSource: "parameter"}, Category: "number", Parameters: []string{"FREQUENCY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "number", Parameters: []string{"LEVEL", "LEVEL_2"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SCHEDULE_SWITCH", DeviceClass: "switch", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "schedule_switch", Parameters: nil, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "HEATING_COOLING", DeviceClass: "", EntityCategory: "config", Icon: "", TranslationKey: "heating_cooling", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "select", Parameters: []string{"HEATING_COOLING"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "AIR_PRESSURE", DeviceClass: "pressure", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "hPa", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"AIR_PRESSURE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "APPARENT_TEMPERATURE", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "°C", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"APPARENT_TEMPERATURE", "FROST_POINT"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "BRIGHTNESS", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "brightness", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"BRIGHTNESS"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CARRIER_SENSE_LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "mdi:radio-tower", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"CARRIER_SENSE_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CODE_ID", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"CODE_ID"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CONCENTRATION", DeviceClass: "carbon_dioxide", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "ppm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"CONCENTRATION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CURRENT", DeviceClass: "current", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "mA", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"CURRENT"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DEW_POINT", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "dew_point", UnitOfMeasurement: "°C", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DEWPOINT", "DEW_POINT"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DEW_POINT_SPREAD", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "K", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DEW_POINT_SPREAD"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DIRECTION", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "direction", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ACTIVITY_STATE", "DIRECTION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DIRT_LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DIRT_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DOOR_STATE", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "door_state", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DOOR_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "DUTY_CYCLE_LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "mdi:radio-tower", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"DUTY_CYCLE_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "ENERGY_COUNTER", DeviceClass: "energy", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "Wh", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ENERGY_COUNTER", "ENERGY_COUNTER_FEED_IN"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "ENTHALPY", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "mdi:fire", TranslationKey: "", UnitOfMeasurement: "kJ/kg", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ENTHALPY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "FILLING_LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"FILLING_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "FREQUENCY", DeviceClass: "frequency", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "Hz", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"FREQUENCY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "GAS_ENERGY_COUNTER", DeviceClass: "gas", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"GAS_ENERGY_COUNTER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "GAS_FLOW", DeviceClass: "volume_flow_rate", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "m³/h", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"GAS_FLOW"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "GAS_POWER", DeviceClass: "", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"GAS_POWER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "GAS_VOLUME", DeviceClass: "gas", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"GAS_VOLUME"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "HUMIDITY", DeviceClass: "humidity", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"HUMIDITY", "ACTUAL_HUMIDITY"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "IEC_ENERGY_COUNTER", DeviceClass: "energy", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "kWh", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"IEC_ENERGY_COUNTER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "IEC_POWER", DeviceClass: "power", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "W", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"IEC_POWER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "ILLUMINATION", DeviceClass: "illuminance", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "lx", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ILLUMINATION", "AVERAGE_ILLUMINATION", "CURRENT_ILLUMINATION", "HIGHEST_ILLUMINATION", "LOWEST_ILLUMINATION", "LUX"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "IP_ADDRESS", DeviceClass: "", StateClass: "", EntityCategory: "diagnostic", Icon: "mdi:ip-network", TranslationKey: "", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"IP_ADDRESS"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter", Multiplier: entityFloat64Ptr(100.0)}, Category: "sensor", Parameters: []string{"LEVEL", "LEVEL_2"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "LOCK_STATE", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "lock_state", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"LOCK_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "LOCK_STATE_REASON", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "lock_state_reason", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"LOCK_STATE_REASON"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MASS_CONCENTRATION_PM_1", DeviceClass: "pm1", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "µg/m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"MASS_CONCENTRATION_PM_1", "MASS_CONCENTRATION_PM_1_24H_AVERAGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MASS_CONCENTRATION_PM_10", DeviceClass: "pm10", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "µg/m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"MASS_CONCENTRATION_PM_10", "MASS_CONCENTRATION_PM_10_24H_AVERAGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MASS_CONCENTRATION_PM_2_5", DeviceClass: "pm25", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "µg/m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"MASS_CONCENTRATION_PM_2_5", "MASS_CONCENTRATION_PM_2_5_24H_AVERAGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "NUMBER_CONCENTRATION_PM_1", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "1/cm³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"NUMBER_CONCENTRATION_PM_1"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "NUMBER_CONCENTRATION_PM_10", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "1/cm³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"NUMBER_CONCENTRATION_PM_10"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "NUMBER_CONCENTRATION_PM_2_5", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "1/cm³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"NUMBER_CONCENTRATION_PM_2_5"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "OPERATING_VOLTAGE", DeviceClass: "voltage", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "V", SuggestedDisplayPrecision: entityIntPtr(1), EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"BATTERY_STATE", "OPERATING_VOLTAGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "OPERATING_VOLTAGE_LEVEL", DeviceClass: "battery", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"OPERATING_VOLTAGE_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "POWER", DeviceClass: "power", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "W", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"POWER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "RAIN_COUNTER", DeviceClass: "", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "rain_counter_total", UnitOfMeasurement: "mm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"RAIN_COUNTER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "RSSI", DeviceClass: "signal_strength", StateClass: "measurement", EntityCategory: "diagnostic", Icon: "", TranslationKey: "", UnitOfMeasurement: "dBm", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"RSSI_DEVICE", "RSSI_PEER"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SMOKE_DETECTOR_ALARM_STATUS", DeviceClass: "enum", StateClass: "", EntityCategory: "", Icon: "", TranslationKey: "smoke_detector_alarm_status", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"SMOKE_DETECTOR_ALARM_STATUS"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SMOKE_LEVEL", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"SMOKE_LEVEL"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SUNSHINEDURATION", DeviceClass: "", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "sunshine_duration", UnitOfMeasurement: "min", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"SUNSHINEDURATION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "TEMPERATURE", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "°C", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"ACTUAL_TEMPERATURE", "TEMPERATURE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "TYPICAL_PARTICLE_SIZE", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "µm", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"TYPICAL_PARTICLE_SIZE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "VALUE", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"VALUE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "VAPOR_CONCENTRATION", DeviceClass: "absolute_humidity", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "g/m³", SuggestedDisplayPrecision: nil, EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"VAPOR_CONCENTRATION"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "VOLTAGE", DeviceClass: "voltage", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "V", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"VOLTAGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WATER_FLOW", DeviceClass: "volume_flow_rate", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "L/min", SuggestedDisplayPrecision: entityIntPtr(1), NameSource: "parameter"}, Category: "sensor", Parameters: []string{"WATER_FLOW"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WATER_VOLUME", DeviceClass: "water", StateClass: "total_increasing", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "L", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"WATER_VOLUME"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WATER_VOLUME_SINCE_OPEN", DeviceClass: "water", StateClass: "total", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "L", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"WATER_VOLUME_SINCE_OPEN"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WIND_DIR", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "wind_dir", UnitOfMeasurement: "°", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"WIND_DIR", "WIND_DIR_RANGE", "WIND_DIRECTION", "WIND_DIRECTION_RANGE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WIND_SPEED", DeviceClass: "wind_speed", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "wind_speed", UnitOfMeasurement: "km/h", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: []string{"WIND_SPEED"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "SWSD", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "siren", Parameters: nil, Devices: []string{"HmIP-SWSD"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "AUTO_RELOCK_STATE", DeviceClass: "switch", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "switch", Parameters: []string{"AUTO_RELOCK_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "INHIBIT", DeviceClass: "switch", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "switch", Parameters: []string{"INHIBIT"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "MOTION_DETECTION_ACTIVE", DeviceClass: "switch", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "switch", Parameters: []string{"MOTION_DETECTION_ACTIVE", "PRESENCE_DETECTION_ACTIVE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "OUTLET", DeviceClass: "outlet", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""}, Category: "switch", Parameters: nil, Devices: []string{"HmIP-PS"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "PERMISSION_STATE", DeviceClass: "switch", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false)}, Category: "switch", Parameters: []string{"PERMISSION_STATE"}, Devices: nil, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "WSM", DeviceClass: "water", EntityCategory: "", Icon: "", TranslationKey: "irrigation_valve", UnitOfMeasurement: ""}, Category: "valve", Parameters: nil, Devices: []string{"ELV-SH-WSM ", "HmIP-WSM"}, Unit: "", Postfix: "", VarNameContains: "", Priority: 0},
	{Description: HARegistryDescription{Key: "CONCENTRATION_FALLBACK", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "g/m³", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: nil, Devices: nil, Unit: "g/m³", Postfix: "", VarNameContains: "", Priority: -100},
	{Description: HARegistryDescription{Key: "PERCENTAGE_FALLBACK", DeviceClass: "", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "%", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: nil, Devices: nil, Unit: "%", Postfix: "", VarNameContains: "", Priority: -100},
	{Description: HARegistryDescription{Key: "PRESSURE_BAR_FALLBACK", DeviceClass: "pressure", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "bar", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: nil, Devices: nil, Unit: "bar", Postfix: "", VarNameContains: "", Priority: -100},
	{Description: HARegistryDescription{Key: "TEMPERATURE_CELSIUS_FALLBACK", DeviceClass: "temperature", StateClass: "measurement", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "°C", SuggestedDisplayPrecision: nil, NameSource: "parameter"}, Category: "sensor", Parameters: nil, Devices: nil, Unit: "°C", Postfix: "", VarNameContains: "", Priority: -100},
}

// haRegistryDescriptionDefaults is the last-resort per-category
// description, consulted by [HARegistryDescriptionLookup] when no rule
// matches.
var haRegistryDescriptionDefaults = map[string]HARegistryDescription{
	"button":     {Key: "button_default", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "button_press", UnitOfMeasurement: "", EnabledByDefault: entityBoolPtr(false), NameSource: "parameter"},
	"hub_button": {Key: "hub_button_default", DeviceClass: "", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: "", NameSource: "parameter"},
	"hub_switch": {Key: "hub_switch_default", DeviceClass: "switch", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""},
	"select":     {Key: "select_default", DeviceClass: "", EntityCategory: "config", Icon: "", TranslationKey: "", UnitOfMeasurement: ""},
	"switch":     {Key: "switch_default", DeviceClass: "switch", EntityCategory: "", Icon: "", TranslationKey: "", UnitOfMeasurement: ""},
}
