// SPDX-License-Identifier: MIT
// Copyright (C) 2026 SukramJ.

package mqtt

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/SukramJ/openccu-loom/pkg/hmenum"
)

// TestBuildSysvarDiscovery_AutoGeneratedCounterFriendlyName pins the friendly,
// localized presentation of CCU-auto-generated counter sysvars: the raw token
// name (svEnergyCounter_<ise_id>_<addr>:<ch>) becomes "Energiezähler Gesamt"
// (de) / "Energy Counter Total" (en) with energy device_class, Wh and a
// cumulative total_increasing state_class — while the stable unique_id keeps
// the raw slug so HA history is not orphaned.
func TestBuildSysvarDiscovery_AutoGeneratedCounterFriendlyName(t *testing.T) {
	t.Parallel()
	cases := []struct {
		locale   string
		wantName string
	}{
		{"de", "Energiezähler Gesamt"},
		{"en", "Energy Counter Total"},
		{"", "Energy Counter Total"}, // default → English
	}
	for _, tc := range cases {
		t.Run("locale="+tc.locale, func(t *testing.T) {
			t.Parallel()
			b := NewDefaultDiscoveryBuilder(NewTopicBuilder("openccu-loom"), "ccu-01").WithLocale(tc.locale)
			b.SetHubInfoFor("ccu-01", HubInfo{Serial: "3014F711A0001234"})

			item := b.BuildSysvarDiscovery("ccu-01", HubSysvarSpec{
				Name:      "svEnergyCounter_14007_0001DBE9915BE4:6",
				ValueType: hmenum.HubValueTypeFloat,
			})
			if !item.OK {
				t.Fatal("expected an OK discovery item")
			}
			if item.Component != string(HAComponentSensor) {
				t.Fatalf("component = %q, want sensor", item.Component)
			}

			var body map[string]any
			if err := json.Unmarshal(item.Payload, &body); err != nil {
				t.Fatalf("unmarshal payload: %v", err)
			}
			if body["name"] != tc.wantName {
				t.Errorf("name = %v, want %q", body["name"], tc.wantName)
			}
			if body["device_class"] != "energy" {
				t.Errorf("device_class = %v, want energy", body["device_class"])
			}
			if body["unit_of_measurement"] != "Wh" {
				t.Errorf("unit_of_measurement = %v, want Wh", body["unit_of_measurement"])
			}
			if body["state_class"] != "total_increasing" {
				t.Errorf("state_class = %v, want total_increasing", body["state_class"])
			}
			// The stable identifier keeps the raw slug — a rename must not orphan
			// HA history / re-key the entity.
			uid, _ := body["unique_id"].(string)
			if !strings.Contains(uid, "sysvar") || strings.Contains(strings.ToLower(uid), "energiez") {
				t.Errorf("unique_id should stay the raw stable slug, got %q", uid)
			}
		})
	}
}

// TestBuildSysvarDiscovery_OperatorSysvarKeepsName ensures a normal,
// operator-named sysvar is untouched by the auto-counter classification.
func TestBuildSysvarDiscovery_OperatorSysvarKeepsName(t *testing.T) {
	t.Parallel()
	b := NewDefaultDiscoveryBuilder(NewTopicBuilder("openccu-loom"), "ccu-01").WithLocale("de")
	b.SetHubInfoFor("ccu-01", HubInfo{Serial: "3014F711A0001234"})

	item := b.BuildSysvarDiscovery("ccu-01", HubSysvarSpec{
		Name:      "Anwesenheit",
		ValueType: hmenum.HubValueTypeFloat,
	})
	if !item.OK {
		t.Fatal("expected an OK discovery item")
	}
	var body map[string]any
	if err := json.Unmarshal(item.Payload, &body); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}
	if body["name"] != "Anwesenheit" {
		t.Errorf("name = %v, want the operator's own name %q", body["name"], "Anwesenheit")
	}
	if _, has := body["device_class"]; has {
		t.Errorf("operator sysvar must not get an auto device_class: %v", body["device_class"])
	}
	if body["state_class"] != "measurement" {
		t.Errorf("state_class = %v, want measurement (plain numeric sensor)", body["state_class"])
	}
}
