// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

//go:build e2e

package harness

import (
	"fmt"
	"strings"
	"time"
)

// configInputs collects every value the config template needs.
// Keeping the inputs in one struct makes the YAML template easy to
// read and to extend without churn through buildConfigYAML's
// signature.
type configInputs struct {
	DataDir      string
	RESTListen   string // ":<port>"
	UIListen     string // ":<port>"
	CallbackPort int
	BinPort      int
	AuthMode     AuthMode
	MQTTBroker   string // "tcp://127.0.0.1:<port>" or ""
	OIDCIssuer   string // "http://127.0.0.1:<port>" or ""
	CCUHost      string // "127.0.0.1"
	CCUXMLRPC    int    // godevccu XML-RPC port
	CCUJSONRPC   int    // godevccu JSON-RPC port (CentralConfig.JSONRPCPort)
	// CheckConnectionInterval overrides the central's check_connection job cadence.
	// Zero uses the compiled-in default. Use a short value (e.g. 5 s) in tests
	// that need fast degraded-state detection.
	CheckConnectionInterval time.Duration
}

// buildConfigYAML returns a complete openccu-loom config that wires
// the daemon for an E2E test run: every listener pinned to a free
// port, persistence inside DataDir, the single central pointed at
// godevccu, all north-bound surfaces enabled by default.
//
// The returned YAML is intentionally written by hand rather than
// marshalled from internal/config types — the harness lives
// separately from production config types so a refactor on the
// production side cannot silently change harness behaviour.
func buildConfigYAML(in configInputs) string {
	basicEnabled := boolYAML(in.AuthMode == AuthBasic || in.AuthMode == AuthSession)
	bearerEnabled := boolYAML(in.AuthMode == AuthToken)
	sessionEnabled := boolYAML(in.AuthMode == AuthSession)
	oidcEnabled := boolYAML(in.AuthMode == AuthOIDC)

	tokensBlock := "        {}\n"
	if in.AuthMode == AuthToken {
		tokensBlock = fmt.Sprintf("        %s: admin\n", AdminToken)
	}

	mqttBlock := "  mqtt:\n    enabled: false\n"
	if in.MQTTBroker != "" {
		// raw_enabled / discovery_enabled MUST be set explicitly: the
		// Go zero-value is false, and `internal/config.applyDefaults`
		// does not flip them — see docs/e2e-testplan.md §11.5 for the
		// doc/code drift this works around.
		mqttBlock = fmt.Sprintf(""+
			"  mqtt:\n"+
			"    enabled: true\n"+
			"    broker_url: %q\n"+
			"    topic_base: openccu-loom\n"+
			"    raw_enabled: true\n"+
			"    discovery_enabled: true\n",
			in.MQTTBroker)
	}

	oidcBlock := "      oidc:\n        enabled: false\n"
	if in.AuthMode == AuthOIDC {
		// The redirect_url MUST match the route mounted on the REST
		// listener (not the UI listener) — the OIDC callback handler
		// lives in internal/north/rest/handlers/oidc.go. Bumping the
		// daemon to listen on a free REST port means we have to embed
		// that port in the redirect URL too, hence the templated
		// substitution.
		oidcBlock = fmt.Sprintf(""+
			"      oidc:\n"+
			"        enabled: true\n"+
			"        issuer: %q\n"+
			"        client_id: openccu-loom-e2e\n"+
			"        redirect_url: \"http://127.0.0.1%s/api/v1/auth/oidc/callback\"\n",
			in.OIDCIssuer, in.RESTListen)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by tests/e2e/harness — DO NOT COMMIT\n")
	fmt.Fprintf(&b, "locale: en\n")
	fmt.Fprintf(&b, "data_dir: %q\n", in.DataDir)
	fmt.Fprintf(&b, "logging:\n  level: info\n  format: json\n")
	fmt.Fprintf(&b, "callback:\n")
	fmt.Fprintf(&b, "  host: 127.0.0.1\n")
	fmt.Fprintf(&b, "  port: %d\n", in.CallbackPort)
	fmt.Fprintf(&b, "  bin_port: %d\n", in.BinPort)
	fmt.Fprintf(&b, "north:\n")
	fmt.Fprintf(&b, "  rest:\n")
	fmt.Fprintf(&b, "    enabled: true\n")
	fmt.Fprintf(&b, "    listen: %q\n", in.RESTListen)
	// CSRF protection is on by default in production; the smoke clients
	// here exchange JSON over loopback without a browser session, so we
	// pin it off explicitly. CSRF behaviour is covered by unit tests
	// in internal/auth.
	fmt.Fprintf(&b, "    csrf_enabled: false\n")
	fmt.Fprintf(&b, "    auth:\n")
	fmt.Fprintf(&b, "      basic_enabled: %s\n", basicEnabled)
	fmt.Fprintf(&b, "      bearer_enabled: %s\n", bearerEnabled)
	fmt.Fprintf(&b, "      session_enabled: %s\n", sessionEnabled)
	fmt.Fprintf(&b, "      users:\n        %s: %q\n", AdminUser, AdminPass)
	fmt.Fprintf(&b, "      tokens:\n%s", tokensBlock)
	fmt.Fprintf(&b, "%s", oidcBlock)
	_ = oidcEnabled // currently encoded inside oidcBlock
	fmt.Fprintf(&b, "  ui:\n    enabled: true\n    listen: %q\n", in.UIListen)
	fmt.Fprintf(&b, "%s", mqttBlock)
	fmt.Fprintf(&b, "centrals:\n")
	fmt.Fprintf(&b, "  - name: ccu-e2e\n")
	fmt.Fprintf(&b, "    host: %s\n", in.CCUHost)
	fmt.Fprintf(&b, "    port: %d\n", in.CCUXMLRPC)
	if in.CCUJSONRPC > 0 {
		// godevccu's JSON-RPC binds to an ephemeral port; pin it so
		// the daemon's seed pipeline (ReGa.runScript, Program.getAll,
		// Device.listAllDetail) reaches the simulator instead of
		// dialling the default port 80 on the host.
		fmt.Fprintf(&b, "    json_rpc_port: %d\n", in.CCUJSONRPC)
	}
	// godevccu's CCU personality enables JSON-RPC auth with the
	// canonical "Admin" / "" credentials (see
	// tests/integration/godevccu.go startMockCCUOpenCCU). Without
	// this the seed calls 401 with json-rpc -32002.
	fmt.Fprintf(&b, "    username: Admin\n")
	fmt.Fprintf(&b, "    password: \"\"\n")
	fmt.Fprintf(&b, "    interfaces:\n      - HmIP-RF\n")
	if in.CheckConnectionInterval > 0 {
		// Express as a Go duration string (e.g. "5s") so the yaml unmarshaller
		// can decode it into time.Duration via the standard YAML duration codec.
		fmt.Fprintf(&b, "    check_connection_interval: %s\n", in.CheckConnectionInterval.String())
	}
	return b.String()
}

func boolYAML(b bool) string {
	if b {
		return "true"
	}
	return "false"
}
