// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

package closure_test

import (
	"encoding/json"
	"testing"

	"github.com/SukramJ/openccu-loom/internal/north/matter/cluster/closure"
	clusterwire "github.com/SukramJ/openccu-loom/internal/north/matter/cluster/wire"
	matterparity "github.com/SukramJ/openccu-loom/internal/north/matter/parity"
)

// The subset of the matter.js schema snapshot these tests read. The
// snapshot is the matter.js HEAD pin regenerated by
// `make generate-matter-schema`, so asserting against it is asserting
// against matter.js rather than against a second hand-typed copy of the
// same numbers — which would agree with the code and with nothing else.
type (
	matterFieldEntry struct {
		ID          uint32 `json:"id"`
		Name        string `json:"name"`
		Conformance string `json:"conformance"`
	}
	matterFeatureEntry struct {
		Name        string `json:"name"`
		Conformance string `json:"conformance"`
	}
	matterClusterEntry struct {
		ID         uint32               `json:"id"`
		Name       string               `json:"name"`
		Revision   uint16               `json:"revision"`
		Attributes []matterFieldEntry   `json:"attributes"`
		Commands   []matterFieldEntry   `json:"commands"`
		Events     []matterFieldEntry   `json:"events"`
		Features   []matterFeatureEntry `json:"features"`
	}
	matterSchemaEnvelope struct {
		Clusters []matterClusterEntry `json:"clusters"`
	}
)

func closureSchema(t *testing.T) matterClusterEntry {
	t.Helper()
	var s matterSchemaEnvelope
	if err := json.Unmarshal(matterparity.SchemaJSON(), &s); err != nil {
		t.Fatalf("unmarshal matter-schema-snapshot.json: %v", err)
	}
	for i := range s.Clusters {
		if s.Clusters[i].ID == clusterwire.ClosureControlClusterID {
			return s.Clusters[i]
		}
	}
	t.Fatalf("matter.js schema has no cluster 0x%04X (ClosureControl)", clusterwire.ClosureControlClusterID)
	return matterClusterEntry{}
}

// idOf resolves a named element's ID from the schema, failing when
// matter.js no longer carries that name. A rename is a drift the port has
// to follow, not a case to skip over.
func idOf(t *testing.T, kind string, entries []matterFieldEntry, name string) uint32 {
	t.Helper()
	for _, e := range entries {
		if e.Name == name {
			return e.ID
		}
	}
	t.Fatalf("matter.js ClosureControl has no %s named %q", kind, name)
	return 0
}

// TestParityMatterJS_ClosureControlClusterRevision pins the cluster
// revision against matter.js HEAD.
func TestParityMatterJS_ClosureControlClusterRevision(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	if closure.ClusterRevision != js.Revision {
		t.Errorf("ClusterRevision = %d, want %d (matter.js HEAD for %s 0x%04X)",
			closure.ClusterRevision, js.Revision, js.Name, js.ID)
	}
}

// TestParityMatterJS_ClosureControlAttributeIDs pins every attribute-ID
// constant against matter.js HEAD by name.
func TestParityMatterJS_ClosureControlAttributeIDs(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	cases := []struct {
		name string
		got  uint32
	}{
		{"CountdownTime", clusterwire.ClosureControlAttrCountdownTime},
		{"MainState", clusterwire.ClosureControlAttrMainState},
		{"CurrentErrorList", clusterwire.ClosureControlAttrCurrentErrorList},
		{"OverallCurrentState", clusterwire.ClosureControlAttrOverallCurrentState},
		{"OverallTargetState", clusterwire.ClosureControlAttrOverallTargetState},
		{"LatchControlModes", clusterwire.ClosureControlAttrLatchControlModes},
	}
	for _, tc := range cases {
		if want := idOf(t, "attribute", js.Attributes, tc.name); tc.got != want {
			t.Errorf("%s = 0x%04X, want 0x%04X (matter.js HEAD)", tc.name, tc.got, want)
		}
	}
}

// TestParityMatterJS_ClosureControlCommandIDs pins every command-ID
// constant against matter.js HEAD by name.
func TestParityMatterJS_ClosureControlCommandIDs(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	cases := []struct {
		name string
		got  uint32
	}{
		{"Stop", clusterwire.ClosureControlCmdStop},
		{"MoveTo", clusterwire.ClosureControlCmdMoveTo},
		{"Calibrate", clusterwire.ClosureControlCmdCalibrate},
	}
	for _, tc := range cases {
		if want := idOf(t, "command", js.Commands, tc.name); tc.got != want {
			t.Errorf("%s = 0x%02X, want 0x%02X (matter.js HEAD)", tc.name, tc.got, want)
		}
	}
}

// TestParityMatterJS_ClosureControlEventIDs pins every event-ID constant
// against matter.js HEAD by name.
func TestParityMatterJS_ClosureControlEventIDs(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	cases := []struct {
		name string
		got  uint32
	}{
		{"OperationalError", clusterwire.ClosureControlEventOperationalError},
		{"MovementCompleted", clusterwire.ClosureControlEventMovementCompleted},
		{"EngageStateChanged", clusterwire.ClosureControlEventEngageStateChanged},
		{"SecureStateChanged", clusterwire.ClosureControlEventSecureStateChanged},
	}
	for _, tc := range cases {
		if want := idOf(t, "event", js.Events, tc.name); tc.got != want {
			t.Errorf("%s = 0x%02X, want 0x%02X (matter.js HEAD)", tc.name, tc.got, want)
		}
	}
}

// TestParityMatterJS_ClosureControlFeatureBits pins each feature bit
// against its position in matter.js's feature list.
//
// The snapshot carries features in declaration order and the Matter
// FeatureMap assigns bit N to the Nth declared feature, so the index is
// the bit. A feature inserted upstream shifts every later bit, which is
// exactly the drift this catches — and the kind that produces a
// FeatureMap a controller reads as a different device.
func TestParityMatterJS_ClosureControlFeatureBits(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	cases := []struct {
		name string
		got  uint32
	}{
		{"PS", clusterwire.ClosureControlFeaturePositioning},
		{"LT", clusterwire.ClosureControlFeatureMotionLatching},
		{"IS", clusterwire.ClosureControlFeatureInstantaneous},
		{"SP", clusterwire.ClosureControlFeatureSpeed},
		{"VT", clusterwire.ClosureControlFeatureVentilation},
		{"PD", clusterwire.ClosureControlFeaturePedestrian},
		{"CL", clusterwire.ClosureControlFeatureCalibration},
		{"PT", clusterwire.ClosureControlFeatureProtection},
		{"MO", clusterwire.ClosureControlFeatureManuallyOperable},
	}
	for _, tc := range cases {
		bit := -1
		for i, f := range js.Features {
			if f.Name == tc.name {
				bit = i
				break
			}
		}
		if bit < 0 {
			t.Errorf("matter.js ClosureControl has no feature %q", tc.name)
			continue
		}
		if want := uint32(1) << uint(bit); tc.got != want {
			t.Errorf("feature %s = 0x%X, want 0x%X (bit %d in matter.js HEAD declaration order)",
				tc.name, tc.got, want, bit)
		}
	}
}

// TestParityMatterJS_ClosureControlVentilationRequiresPositioning pins the
// conformance rule behind the advertised feature map.
//
// Ventilation is "[PS]" in matter.js, so a server advertising VT without
// PS describes a device the spec does not allow. Nothing at runtime
// rejects that combination — a controller simply reads a feature map that
// does not add up.
func TestParityMatterJS_ClosureControlVentilationRequiresPositioning(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)

	var ventConformance string
	for _, f := range js.Features {
		if f.Name == "VT" {
			ventConformance = f.Conformance
		}
	}
	if ventConformance != "[PS]" {
		t.Fatalf("matter.js VT conformance = %q, want \"[PS]\" — the feature map below assumes it", ventConformance)
	}

	fm := closure.PositioningVentilationFeatureMap
	if fm&clusterwire.ClosureControlFeatureVentilation == 0 {
		t.Error("PositioningVentilationFeatureMap does not advertise Ventilation")
	}
	if fm&clusterwire.ClosureControlFeaturePositioning == 0 {
		t.Error("PositioningVentilationFeatureMap advertises Ventilation without Positioning, " +
			"which its \"[PS]\" conformance forbids")
	}
}

// TestParityMatterJS_ClosureControlServesEveryMandatoryAttribute pins that
// the server answers every attribute matter.js marks mandatory under the
// advertised feature set.
//
// A mandatory attribute the server does not resolve reads as "unsupported
// attribute", which a strict controller treats as a malformed cluster.
func TestParityMatterJS_ClosureControlServesEveryMandatoryAttribute(t *testing.T) {
	t.Parallel()
	js := closureSchema(t)
	srv := closure.NewControlServer(closure.Config{})

	served := make(map[uint32]bool)
	for _, id := range srv.MatterAttributes() {
		served[id] = true
	}

	for _, attr := range js.Attributes {
		if attr.Conformance != "M" {
			continue
		}
		if !served[attr.ID] {
			t.Errorf("attribute %s (0x%04X) is mandatory in matter.js HEAD but the server does not serve it",
				attr.Name, attr.ID)
			continue
		}
		if _, ok := srv.MatterRead(attr.ID); !ok {
			t.Errorf("attribute %s (0x%04X) is listed in MatterAttributes but MatterRead declines it",
				attr.Name, attr.ID)
		}
	}
}

// TestParityMatterJS_ControlServerListsOnlyServableAttributes is the
// reverse direction: an attribute the server advertises must actually
// resolve. The pair matters — either half alone passes with a list that
// has nothing to do with what MatterRead answers.
func TestParityMatterJS_ControlServerListsOnlyServableAttributes(t *testing.T) {
	t.Parallel()
	srv := closure.NewControlServer(closure.Config{})
	for _, id := range srv.MatterAttributes() {
		if _, ok := srv.MatterRead(id); !ok {
			t.Errorf("MatterAttributes lists 0x%04X but MatterRead declines it", id)
		}
	}
	for _, id := range srv.MatterReportable() {
		if _, ok := srv.MatterRead(id); !ok {
			t.Errorf("MatterReportable lists 0x%04X but MatterRead declines it", id)
		}
	}
}
