// SPDX-License-Identifier: MIT
// Copyright (C) 2026 openccu-loom authors.
//
// Code generated by script/generate_profiles.py. DO NOT EDIT.
// Generated at: 2026-07-03T12:34:10+00:00

package custom

import "github.com/SukramJ/openccu-loom/pkg/hmenum"

// GeneratedDefaultDataPointCount is the number of channel-offset
// entries that DefaultDataPoints exposes.
const GeneratedDefaultDataPointCount = 3

// DefaultDataPoints mirrors the Python reference implementation's
// per-channel-offset default data-point table. Profile authors inherit
// these generic data points unless
// [ProfileConfig.IncludeDefaultDataPoints] is false. Tuple keys in the
// source are expanded so each channel offset is its own map entry.
var DefaultDataPoints = map[int][]hmenum.Parameter{
	0: {
		hmenum.ParameterActualTemperature,
		hmenum.ParameterDutyCycle,
		hmenum.ParameterDutycycle,
		hmenum.ParameterLowBat,
		hmenum.ParameterLowbat,
		hmenum.ParameterOperatingVoltage,
		hmenum.ParameterRSSIDevice,
		hmenum.ParameterRSSIPeer,
		hmenum.ParameterSabotage,
		hmenum.ParameterTimeOfOperation,
	},
	2: {
		hmenum.ParameterBatteryState,
	},
	4: {
		hmenum.ParameterBatteryState,
	},
}
