// SPDX-License-Identifier: MIT
// Copyright (C) 2026 OpenCCU-Loom authors.

package cover

import (
	"context"
	"testing"

	"github.com/SukramJ/openccu-loom/internal/model/custom"
	"github.com/SukramJ/openccu-loom/internal/model/generic"
	"github.com/SukramJ/openccu-loom/pkg/hmenum"
	"github.com/SukramJ/openccu-loom/pkg/hmproto"
	"github.com/SukramJ/openccu-loom/pkg/hmtypes"

	"github.com/SukramJ/openccu-loom/internal/model/device"
)

// --- Cover deep tests ---

// TestCoverConstructFromChannelWithLevelDP verifies that a Cover built from a
// channel that carries a LEVEL data point has a non-nil Float and can read the
// position.
func TestCoverConstructFromChannelWithLevelDP(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	c, _, level := newRig(t, "HmIP-BROLL:3", w, custom.CoverCapabilities{})

	if c.Float == nil {
		t.Fatal("Cover.Float must not be nil when channel carries LEVEL DP")
	}

	// Not observed yet.
	if _, ok := c.Position(); ok {
		t.Error("Position() must not be observed before any event")
	}

	level.OnEvent(0.6)
	pos, ok := c.Position()
	if !ok {
		t.Fatal("Position() must be observed after OnEvent")
	}
	if pos.Level() != 0.6 {
		t.Errorf("Position().Level() = %v, want 0.6", pos.Level())
	}
}

// TestCoverNilLevelDPGracefullyDegrades verifies that a Cover constructed from
// a channel without a LEVEL DP does not panic and returns safe values.
func TestCoverNilLevelDPGracefullyDegrades(t *testing.T) {
	t.Parallel()

	d := device.New(device.Config{InterfaceID: "HmIP-RF", Address: "ABC0001"})
	// Channel with no LEVEL DP.
	ch := d.AddChannel("HmIP-BROLL:3", 1, "BLIND", hmenum.ParamsetKeyValues)
	c := New(Config{Channel: ch, Writer: &stubWriter{}, Capabilities: custom.CoverCapabilities{}})

	if c.Float != nil {
		t.Error("Cover.Float must be nil when channel has no LEVEL DP")
	}
	if _, ok := c.Position(); ok {
		t.Error("Position() must not be observed when LEVEL DP is absent")
	}
	// Write attempts must error cleanly.
	if err := c.SetPosition(context.Background(), 0.5, hmenum.CommandPriorityHigh); err == nil {
		t.Error("SetPosition must return an error when LEVEL DP is absent")
	}
	// DataPointKey must NOT panic when Float is nil — the autogenerated
	// forwarder previously dispatched to (*DataPoint).DataPointKey on a
	// nil receiver and crashed the daemon during materialisation.
	if got := c.DataPointKey(); got != (hmtypes.DataPointKey{}) {
		t.Errorf("DataPointKey() with nil Float = %v, want zero key", got)
	}
	// Same hazard, different forwarder: Category dispatches through
	// (*DataPoint).Category which dereferences its receiver. The WS
	// custom-DP-list handler hit this on a half-formed Cover.
	if got := c.Category(); got != hmenum.DataPointCategoryUndefined {
		t.Errorf("Category() with nil Float = %v, want undefined", got)
	}
}

// TestCoverOpenSetsLevelMax verifies that Open() sends LEVEL = 1.0 to the CCU.
func TestCoverOpenSetsLevelMax(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	c, _, _ := newRig(t, "HmIP-BROLL:3", w, custom.CoverCapabilities{})

	if err := c.Open(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	if f := w.last.(float64); f != 1.0 {
		t.Errorf("Open() sent LEVEL = %v, want 1.0", f)
	}
}

// TestCoverCloseSetsLevelZero verifies that Close() sends LEVEL = 0.0.
func TestCoverCloseSetsLevelZero(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	c, _, _ := newRig(t, "HmIP-BROLL:3", w, custom.CoverCapabilities{})

	if err := c.Close(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	if f := w.last.(float64); f != 0.0 {
		t.Errorf("Close() sent LEVEL = %v, want 0.0", f)
	}
}

// TestCoverStopForwardsStopDP verifies that Stop() writes STOP=true when
// SupportsStop is set.
func TestCoverStopForwardsStopDP(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	c, _, _ := newRig(t, "HmIP-BROLL:3", w, custom.CoverCapabilities{SupportsStop: true})

	if err := c.Stop(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	if w.last != true {
		t.Errorf("Stop() sent %v, want true (STOP=true)", w.last)
	}
}

// TestCoverSetPositionForwardsValue verifies that SetPosition(0.4) writes 0.4
// on the wire for a plain (non-inverted) cover.
func TestCoverSetPositionForwardsValue(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	c, _, _ := newRig(t, "HmIP-BROLL:3", w, custom.CoverCapabilities{})

	if err := c.SetPosition(context.Background(), 0.4, hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	if f := w.last.(float64); f != 0.4 {
		t.Errorf("SetPosition(0.4) sent %v, want 0.4", f)
	}
	// Domain-level position must also read back as 0.4.
	pos, ok := c.Position()
	if !ok || pos.Level() != 0.4 {
		t.Errorf("Position() = (%v, %v), want (0.4, true)", pos.Level(), ok)
	}
}

// TestCoverIsStateChangeFirstCommandAlwaysTrue verifies that IsStateChange
// returns true when no position has been observed yet (first command always
// goes through), and false when the observed position matches the target.
func TestCoverIsStateChangeFirstCommandAlwaysTrue(t *testing.T) {
	t.Parallel()

	c, _, level := newRig(t, "x", &stubWriter{}, custom.CoverCapabilities{})

	// No position observed → must indicate state change.
	if !c.IsStateChange(0.5) {
		t.Error("IsStateChange must return true when position is not yet observed")
	}

	level.OnEvent(0.5)
	// Same target as current → no state change.
	if c.IsStateChange(0.5) {
		t.Error("IsStateChange must return false when target equals current position")
	}
	// Different target → state change.
	if !c.IsStateChange(0.8) {
		t.Error("IsStateChange must return true when target differs from current position")
	}
}

// --- Blind deep tests ---

// TestBlindTiltPositionReflectsLevel2 verifies that TiltPosition() returns
// the value written to LEVEL_2 via OnEvent on the underlying generic.Float.
func TestBlindTiltPositionReflectsLevel2(t *testing.T) {
	t.Parallel()

	w := &putWriter{}
	d := device.New(device.Config{InterfaceID: "HmIP-RF", Address: "ABC0001"})
	ch := d.AddChannel("VCU3560967:1", 1, "BLIND", hmenum.ParamsetKeyValues)

	mk := func(p hmenum.Parameter) *generic.Float {
		return generic.NewFloat(generic.Spec{
			Key: hmtypes.DataPointKey{
				ChannelAddress: "VCU3560967:1",
				ParamsetKey:    hmenum.ParamsetKeyValues,
				Parameter:      string(p),
			},
			Descriptor: hmproto.ParameterData{
				Type:       hmenum.ParameterTypeFloat,
				Operations: hmenum.OperationsRead | hmenum.OperationsWrite | hmenum.OperationsEvent,
			},
			Writer: w,
		})
	}
	level := mk(hmenum.ParameterLevel)
	level2 := mk(hmenum.ParameterLevel2)
	ch.Put(level)
	ch.Put(level2)

	b := NewBlind(BlindConfig{Channel: ch, Writer: w, Capabilities: custom.CoverCapabilities{SupportsTilt: true}, Kind: BlindKindHM})

	// No tilt observed yet.
	if _, ok := b.TiltPosition(); ok {
		t.Error("TiltPosition() must not be observed before any event")
	}

	// Push a value via the shared LEVEL_2 pointer.
	level2.OnEvent(0.3)
	pos, ok := b.TiltPosition()
	if !ok {
		t.Fatal("TiltPosition() must be observed after level2 OnEvent")
	}
	if pos.Level() != 0.3 {
		t.Errorf("TiltPosition().Level() = %v, want 0.3", pos.Level())
	}
}

// TestBlindOpenTiltSetsLevel2ToMax verifies OpenTilt() → LEVEL_COMBINED encodes
// tilt=1.0 (200/0xc8) in the second hex octet of the HM wire string.
func TestBlindOpenTiltSetsLevel2ToMax(t *testing.T) {
	t.Parallel()

	w := &putWriter{}
	b := newBlindRig(t, "VCU3560967:1", w, custom.CoverCapabilities{SupportsTilt: true}, BlindKindHM)

	if err := b.OpenTilt(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	cc := w.combinedCalls()
	if len(cc) == 0 {
		t.Fatal("OpenTilt must produce at least one LEVEL_COMBINED SetValue")
	}
	got, ok := cc[len(cc)-1].value.(string)
	if !ok {
		t.Fatalf("LEVEL_COMBINED value type = %T, want string", cc[len(cc)-1].value)
	}
	// tilt=1.0 → int(1.0*100*2)=200=0xc8; level=0 → 0x00 → "0x00,0xc8"
	if got != "0x00,0xc8" {
		t.Errorf("OpenTilt: LEVEL_COMBINED = %q, want 0x00,0xc8", got)
	}
}

// TestBlindCloseTiltSetsLevel2ToZero verifies CloseTilt() → LEVEL_COMBINED
// encodes tilt=0 in both octets of the HM wire string.
func TestBlindCloseTiltSetsLevel2ToZero(t *testing.T) {
	t.Parallel()

	w := &putWriter{}
	b := newBlindRig(t, "VCU3560967:1", w, custom.CoverCapabilities{SupportsTilt: true}, BlindKindHM)

	if err := b.CloseTilt(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	cc := w.combinedCalls()
	if len(cc) == 0 {
		t.Fatal("CloseTilt must produce at least one LEVEL_COMBINED SetValue")
	}
	got, ok := cc[len(cc)-1].value.(string)
	if !ok {
		t.Fatalf("LEVEL_COMBINED value type = %T, want string", cc[len(cc)-1].value)
	}
	// tilt=0.0 → 0x00; level=0 → 0x00 → "0x00,0x00"
	if got != "0x00,0x00" {
		t.Errorf("CloseTilt: LEVEL_COMBINED = %q, want 0x00,0x00", got)
	}
}

// --- Garage deep tests ---

// fireDoorState resolves label against dp's own VALUE_LIST and fires the
// resulting raw index as a wire event — mirrors how the resolver projects the
// read-only ENUM parameter DOOR_STATE onto an index-valued Sensor[int32].
func fireDoorState(t *testing.T, dp *generic.Sensor[int32], label string) {
	t.Helper()
	idx, ok := custom.EnumLabelIndex(dp, label)
	if !ok {
		t.Fatalf("label %q not in VALUE_LIST", label)
	}
	dp.OnEvent(idx)
}

// newGarageRig builds a channel carrying DOOR_STATE and SECTION data points
// and returns a Garage against it.
//
//nolint:gocritic // test rig helper — positional returns are the test convention
func newGarageRig(t *testing.T, address string, w Writer) (*Garage, *generic.Sensor[int32], *generic.Sensor[int32]) {
	t.Helper()
	d := device.New(device.Config{InterfaceID: "HmIP-RF", Address: "ABC0001"})
	ch := d.AddChannel(address, 1, "GARAGE_DOOR", hmenum.ParamsetKeyValues)

	doorState := generic.NewIntegerSensor(generic.Spec{
		Key: hmtypes.DataPointKey{
			ChannelAddress: address,
			ParamsetKey:    hmenum.ParamsetKeyValues,
			Parameter:      string(hmenum.ParameterDoorState),
		},
		Descriptor: hmproto.ParameterData{
			Type:       hmenum.ParameterTypeEnum,
			Operations: hmenum.OperationsRead | hmenum.OperationsEvent,
			ValueList:  []string{"UNKNOWN", "OPEN", "CLOSED", "VENTILATION_POSITION"},
		},
	})
	section := generic.NewIntegerSensor(generic.Spec{
		Key: hmtypes.DataPointKey{
			ChannelAddress: address,
			ParamsetKey:    hmenum.ParamsetKeyValues,
			Parameter:      string(hmenum.ParameterSection),
		},
		Descriptor: hmproto.ParameterData{
			Type:       hmenum.ParameterTypeInteger,
			Operations: hmenum.OperationsRead | hmenum.OperationsEvent,
		},
	})
	ch.Put(doorState)
	ch.Put(section)

	g := NewGarage(GarageConfig{Channel: ch, Writer: w, Capabilities: custom.CoverCapabilities{}})
	// Deferred GoTo*Percentage writes fire only via flushGoToWrites so
	// tests stay deterministic.
	neuterGoToTimers(&g.matterGoTo)
	return g, doorState, section
}

// TestGaragePositionDerivesFromDoorState verifies the virtual-position
// mapping: OPEN→1.0, VENTILATION→0.5, CLOSED→0.0.
func TestGaragePositionDerivesFromDoorState(t *testing.T) {
	t.Parallel()

	g, _, _ := newGarageRig(t, "HmIP-MOD-HO:1", &stubWriter{})

	// No state observed yet.
	if _, ok := g.Position(); ok {
		t.Error("Position() must not be observed before any state event")
	}

	cases := []struct {
		state      DoorState
		wantPos    float64
		wantClosed bool
	}{
		{DoorStateOpen, 1.0, false},
		{DoorStateVentilation, 0.5, false},
		{DoorStateClosed, 0.0, true},
	}
	for _, tc := range cases {
		g.OnState(tc.state)
		pos, ok := g.Position()
		if !ok {
			t.Errorf("state=%s: Position() not observed", tc.state)
			continue
		}
		if pos.Level() != tc.wantPos {
			t.Errorf("state=%s: Position().Level() = %v, want %v", tc.state, pos.Level(), tc.wantPos)
		}
		if got := g.IsClosed(); got != tc.wantClosed {
			t.Errorf("state=%s: IsClosed() = %v, want %v", tc.state, got, tc.wantClosed)
		}
	}
}

// TestGarageOpenCommandWritesDoorCommand verifies that Open() writes
// DOOR_COMMAND = "OPEN".
func TestGarageOpenCommandWritesDoorCommand(t *testing.T) {
	t.Parallel()

	w := &stubWriter{}
	g, _, _ := newGarageRig(t, "HmIP-MOD-HO:1", w)

	if err := g.Open(context.Background(), hmenum.CommandPriorityHigh); err != nil {
		t.Fatal(err)
	}
	if w.last.(string) != string(DoorCommandOpen) {
		t.Errorf("Open() sent %v, want %q", w.last, DoorCommandOpen)
	}
}

// TestGarageSetPositionMapsToCommand verifies the three threshold bands of
// SetPosition: >=0.75→OPEN, 0.25..0.75→PARTIAL_OPEN, <0.25→CLOSE.
func TestGarageSetPositionMapsToCommand(t *testing.T) {
	t.Parallel()

	cases := []struct {
		target  float64
		wantCmd DoorCommand
	}{
		{1.0, DoorCommandOpen},
		{0.75, DoorCommandOpen},
		{0.5, DoorCommandPartialOpen},
		{0.25, DoorCommandPartialOpen},
		{0.1, DoorCommandClose},
		{0.0, DoorCommandClose},
	}

	for _, tc := range cases {
		w := &stubWriter{}
		g, _, _ := newGarageRig(t, "HmIP-MOD-HO:1", w)
		if err := g.SetPosition(context.Background(), tc.target, hmenum.CommandPriorityHigh); err != nil {
			t.Errorf("SetPosition(%v) error: %v", tc.target, err)
			continue
		}
		if w.last.(string) != string(tc.wantCmd) {
			t.Errorf("SetPosition(%v) sent %v, want %v", tc.target, w.last, tc.wantCmd)
		}
	}
}
